### ISSUE TITLE
Is there a way to properly uninstall appimaged?

### ISSUE THREAD

**Issue by Leeo97one** [probonopd/go-appimage#108]

**Comment by probonopd** [comment]
`systemctl --user disable appimaged`, then delete the appimaged AppImage.

**Comment by pepa65** [comment]
That would be: `rm ~/.config/systemd/user/appimaged.service`

**Comment by psuter80** [comment]
i found you need to do 4 things: 
1. stop and disable the appimaged user service
```systemctl` --user --now disable appimaged.service```
2. remove the service definition 
```rm ~/.config/systemd/user/appimaged.service```
3. remove the entries appimaged made from your launcher 
```rm ~/.local/share/applications/appimagekit_*```
4. remove the appimaged appimage :)
