### ISSUE TITLE
Deploy -s build. Extract appimage and AppRun manually: $APPDIR and $APPIMAGE env vars not present

### ISSUE THREAD

**Issue by Juuliuus** [probonopd/go-appimage#114]
After testing this method of running appimages because of the solution found to #49 I noticed that my program did not behave as I expected.

Since AppRun is manually executed the $APPDIR and $APPIMAGE env vars are not set, and my program requires those to determine in what state it is running. 

In general, it functions perfectly except in the case of an included library which is loaded at runtime. For example, I include libsqlite lib to make my appimage completely self-contained. I make a decision at run time, based on these env vars, whether to prefer my included lib or not.

This will break some appimages. For example, in ubuntu 16.04, this method then defaulted to the ubunut's libsqlite and not mine. Fortunately in this case that lib still functions with my program. But in other cases, it is very possible that included, loaded at runtime, libraries will fail, and so the manual AppRun method will fail.

I believe the solution should be simple and that is to modify the self-contained section in the AppRun shell script to export those vars if they are not already set.

**Comment by probonopd** [comment]
> Since AppRun is manually executed the $APPDIR and $APPIMAGE env vars are not set, and my program requires those to determine in what state it is running.

A program should never rely on those because as you write, they are only set when run from an AppImage. What in your applciation needs those and can't be done in another way?

**Comment by Juuliuus** [comment]
Ahhh, Well then it was a mis-understanding on my part. I had figured, whether run from an *.AppImage or a manually executed AppRun, there would be some indication in the environment to help the programmer know where and/or how it was being run.

Of course, I can change my program to simply search for a relative path holding my runtime deployed library and act accordingly. The only thing I don't like about this is that it isn't precise, I need to guess a little bit about what to do. An env var set by AppRun would be precise, just like appdir and appimage are.

No worries if you see this as a non-issue, if so feel free to close it. I will be looking at my program to see what I can do to divorce its knowledge of AppImages and use other cues.

**Comment by probonopd** [comment]
> Of course, I can change my program to simply search for a relative path holding my runtime deployed library and act accordingly. 

Yes, this is the recommended way.

Please feel free to comment if you think this needs to be reopened later on.
