### ISSUE TITLE
Docker issue in local machine

### ISSUE THREAD

**Issue by manorit2001** [probonopd/go-appimage#117]
I am getting this error when using this app image after extracting and running in docker

![image](https://user-images.githubusercontent.com/40723245/102919386-c67cd480-44ae-11eb-8d36-29dc65af7163.png)

What am I missing here? The same script works fine when running without docker

**Comment by probonopd** [comment]
What does `which file` say?
Looks like you are missing the `file` command line tool?

**Comment by manorit2001** [comment]
Yes, the `file` command was missing in the docker, it worked after installing it. Thanks for your help
