### ISSUE TITLE
appimaged doesn't work

### ISSUE THREAD

**Issue by Foro38** [probonopd/go-appimage#133]
I did:

`wget https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-640-x86_64.AppImage`
`chmod +x appimaged-640-x86_64.AppImage`
`./appimaged-640-x86_64.AppImage`

Then I get this error

`2021/02/27 23:50:35 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.`
`2021/02/27 23:50:35 xxxxxxxxxxxxxxxxxxxx ERROR: notification: The name org.freedesktop.Notifications was not provided by any .service files`
`

**Comment by probonopd** [comment]
Apparently you are not running on one of the supported Live systems.

**Comment by Dyrimon** [comment]
> Apparently you are not running on one of the supported Live systems.

Hello, I'm experiencing the same issue on Fedora 33 Cinnamon edition. Could you please tell me which operating systems are actually supported? Thanks.

**Comment by Dyrimon** [comment]
My error says:
```
./appimaged-640-x86_64.AppImage
appimaged-640-x86_64.AppImage 640
2021/03/16 18:34:13 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2021/03/16 18:34:13 main: PATH: /opt:/home/fedora/Desktop:/home/fedora/Downloads:/tmp/.mount_appimaWvMqe9/usr/bin:/home/fedora/.local/bin:/home/fedora/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
This process based on /proc/self/exe: /tmp/.mount_appimaWvMqe9/usr/bin/appimaged
Terminating other running processes with that name...
In the future, would send SIGTERM to 54675
```

**Comment by Dyrimon** [comment]
@probonopd Hi, new update. After seemingly failing the first time, waiting a while gives another output in the terminal and actually adds the appimage I downloaded (Notable note app) from the Downloads folder.
```
2021/03/16 18:44:19 Deleted 1 desktop files from /home/fedora/.local/share/applications/; use -v to see details
2021/03/16 18:44:19 Probably not launched by systemd (please file an issue if this is wrong)
2021/03/16 18:44:19 Manually launched, not by systemd. Check if enabled in systemd...
2021/03/16 18:44:19 /etc/systemd/user/appimaged.service does not exist
2021/03/16 18:44:19 Creating ~/.config/systemd/user/appimaged.service
2021/03/16 18:44:19 thisai.path: /home/fedora/Downloads/appimaged-640-x86_64.AppImage
2021/03/16 18:44:20 /usr/bin/systemctl --user status appimaged
2021/03/16 18:44:20 exit status 3
2021/03/16 18:44:20 Enabling systemd service...
2021/03/16 18:44:21 Starting systemd service...
2021/03/16 18:44:21 Exiting...
```
And  the desktop notification says appimage added. So it's working as intended.

BTW, what is the recommended way to uninstall `appimaged` if I want it? Thanks.

**Comment by CalebQ42** [comment]
@Dyrimon as the notification says, it's just a warning that it might not work on your system as it's not the intended testing environment, but it's still working unless it runs into an actual error.

@Foro38 it seems like the error your having is related to his system not providing org.freedesktop.Notification, presumably when it tries to show the warning as a desktop notification. Are you possibly trying to run the app without a DE or with a DE without notifications? Either way we should probably not make notifications completely necessary.

**Comment by probonopd** [comment]
We are currently testing on a Ubuntu bionic Live ISO.
Given your information, I have also tested it on a Fedora 33 Live ISO and it is working for me.

![f33-1](https://user-images.githubusercontent.com/2480569/111354383-8df02f80-8686-11eb-8d02-73e590681205.png)

![f33-2](https://user-images.githubusercontent.com/2480569/111354391-8fb9f300-8686-11eb-8a35-8b9efec7fccc.png)

I don't know whether it works on recent versions of Fedora that have been installed to hard disk.

Originally I wanted to white-list only the distributions we have specifically tested on, and that we actively can support.

In https://github.com/probonopd/go-appimage/issues/46
@KaKi87 suggested that we should open it up for unknown/unsupported distributions as well, hence I had temporarily relaxed the restriction in https://github.com/probonopd/go-appimage/commit/f1ebcce70dae0ab9a671604261d4fd46be88384f with the result that it might or might not work.

**Comment by Foro38** [comment]
I installed a notification manager and the issue is gone. <3

**Comment by Foro38** [comment]
I installed a notification manager and now I get this error instead:
`appimaged-640-x86_64.AppImage 640`
`2021/03/17 00:57:08 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.`
`2021/03/17 00:57:08 main: PATH: /usr/local/bin:/opt:/home/foro/Applications:/home/foro/Desktop:/home/foro/Downloads:/tmp/.mount_appimaXivyPa/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
`This process based on /proc/self/exe: /tmp/.mount_appimaXivyPa/usr/bin/appimaged`
Terminating other running processes with that name...`
`In the future, would send SIGTERM to 33138`
`2021/03/17 00:57:08 Deleted 1 desktop files from /home/foro/.local/share/applications/; use -v to see details`
`2021/03/17 00:57:08 Probably not launched by systemd (please file an issue if this is wrong)`
`2021/03/17 00:57:08 Manually launched, not by systemd. Check if enabled in systemd...`
`2021/03/17 00:57:08 /etc/systemd/user/appimaged.service does not exist`
`2021/03/17 00:57:08 Creating ~/.config/systemd/user/appimaged.service`
`2021/03/17 00:57:08 thisai.path: /home/foro/applimage/appimaged-640-x86_64.AppImage`
`2021/03/17 00:57:08 Restarting via systemd...`

I am using arch linux with i3 wm

**Comment by probonopd** [comment]
@Foro38 which system are you trying to run this on?

**Comment by mtsbh** [comment]
Same problem here. After `~/Applications/appimaged-*.AppImage` I received: 
```
appimaged-754-x86_64.AppImage 108
2023/02/07 06:24:48 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2023/02/07 06:24:48 main: PATH: /usr/local/bin:/opt:/home/Applications:/home/.local/bin:/home/Desktop:/home/Downloads:/tmp/.mount_appimajLkDmk/usr/bin:/home/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
This process based on /proc/self/exe: /tmp/.mount_appimajLkDmk/usr/bin/appimaged
Terminating other running processes with that name...
2023/02/07 06:24:48 Deleted 0 desktop files from /home/.local/share/applications/; use -v to see details
2023/02/07 06:24:48 Probably not launched by systemd (please file an issue if this is wrong)
2023/02/07 06:24:48 Manually launched, not by systemd. Check if enabled in systemd...
2023/02/07 06:24:48 /etc/systemd/user/appimaged.service does not exist
2023/02/07 06:24:48 Creating ~/.config/systemd/user/appimaged.service
2023/02/07 06:24:48 thisai.path: /home/Applications/appimaged-754-x86_64.AppImage
2023/02/07 06:24:48 /usr/bin/systemctl --user status appimaged
2023/02/07 06:24:48 exit status 3
2023/02/07 06:24:48 Enabling systemd service...
2023/02/07 06:24:48 Starting systemd service...
2023/02/07 06:24:48 appimaged should now be running via systemd. To check this, run
2023/02/07 06:24:48 /usr/bin/systemctl -l --no-pager --user status appimaged
```
Ubuntu 22.04

**Comment by CalebQ42** [comment]
> Same problem here. After `~/Applications/appimaged-*.AppImage` I received:
> 
> ```
> appimaged-754-x86_64.AppImage 108
> 2023/02/07 06:24:48 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
> 2023/02/07 06:24:48 main: PATH: /usr/local/bin:/opt:/home/Applications:/home/.local/bin:/home/Desktop:/home/Downloads:/tmp/.mount_appimajLkDmk/usr/bin:/home/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
> This process based on /proc/self/exe: /tmp/.mount_appimajLkDmk/usr/bin/appimaged
> Terminating other running processes with that name...
> 2023/02/07 06:24:48 Deleted 0 desktop files from /home/.local/share/applications/; use -v to see details
> 2023/02/07 06:24:48 Probably not launched by systemd (please file an issue if this is wrong)
> 2023/02/07 06:24:48 Manually launched, not by systemd. Check if enabled in systemd...
> 2023/02/07 06:24:48 /etc/systemd/user/appimaged.service does not exist
> 2023/02/07 06:24:48 Creating ~/.config/systemd/user/appimaged.service
> 2023/02/07 06:24:48 thisai.path: /home/Applications/appimaged-754-x86_64.AppImage
> 2023/02/07 06:24:48 /usr/bin/systemctl --user status appimaged
> 2023/02/07 06:24:48 exit status 3
> 2023/02/07 06:24:48 Enabling systemd service...
> 2023/02/07 06:24:48 Starting systemd service...
> 2023/02/07 06:24:48 appimaged should now be running via systemd. To check this, run
> 2023/02/07 06:24:48 /usr/bin/systemctl -l --no-pager --user status appimaged
> ```
> 
> Ubuntu 22.04

This looks like it is working correctly and appimaged is now running as a systemd service. You can check this by running `systemctl --user status appimaged`
