### ISSUE TITLE
Continuous build should not contain version number

### ISSUE THREAD

**Issue by sjdrc** [probonopd/go-appimage#151]
I have scripts that fetch appimagetool, but in the continuous build on this repo, you put the version number into the filename, making it impossible to reliably download the image.

Can you please either omit the version number from the filename, or do actual versioned releases with stable URLs.

**Comment by sjdrc** [comment]
@probonopd I see that the latest builds now have `-1-` in the filename. Is this name going to stay the same going forwards?

**Comment by probonopd** [comment]
Works as intended again.
