### ISSUE TITLE
Cannot use at all without FUSE

### ISSUE THREAD

**Issue by piegamesde** [probonopd/go-appimage#154]
Is the basic usage and options for `appimagetool` documented somewhere? I tried using my existing commands from the C implementation as drop-in replacement, but it didn't work in a way that suggests my arguments were interpreted in a wrong way:

```
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
Failed to open libnotify.

open dir error: No such file or directory
```

My command is `${appImageGo} ${appDirContents} $out` and all I want to do is to convert a folder into an AppImage.

**Comment by probonopd** [comment]
* Your system seems to not have a working FUSE setup. See https://github.com/AppImage/AppImageKit/wiki/FUSE for more information.
* Also, your system seems to not have libnotify?

**Comment by piegamesde** [comment]
I know, I'm running the command in a sandbox. Are there any reasons for which *building an AppImage* requires either of them? To me, it sounds like "zip a few files, compile a bootstrap binary and pack it into an ELF", from which I can't deduce a requirement for FUSE. Furthermore, the C binary does not seem require them, as I tried it out in the same environment.

**Comment by piegamesde** [comment]
Forget all what I said. I simply ran `./appimagetool-go --help` and still got the error message:

```
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
Failed to open libnotify.

open dir error: No such file or directory
```

Not sure about my previous comment, but I think requiring this dependency just to print the help can safely be called a bug.

**Comment by probonopd** [comment]
`appimagetool-go` is contained inside an AppImage, and AppImages need FUSE to run. Please see https://github.com/AppImage/AppImageKit/wiki/FUSE for more information.
Works as designed. AppImages need FUSE, and there is a documented workaround for those systems that don't have a proper FUSE setup.

**Comment by piegamesde** [comment]
Oooh of course, thanks! I packaged it manually and now it works as intended.
