### ISSUE TITLE
appimagelauncher considered detected, despite uninstalled

### ISSUE THREAD

**Issue by almereyda** [probonopd/go-appimage#165]
In #164 we learned, that `appimaged`/`go-appimage` knows a way to detect *Other AppImage integration daemon*s. In this case it asks:

> Please uninstall appimagelauncher first, then try again.

This is unfortunate, since the system does not have it installed at the moment, and was rebooted since removal of the well known compaion:

```shell
$ sudo apt show -a appimagelauncher 2>/dev/null | grep Status
Status: deinstall ok config-files
```

**Comment by probonopd** [comment]
Is this a duplicate of https://github.com/probonopd/go-appimage/issues/126?

**Comment by almereyda** [comment]
Thank you for the pointer! Didn't find that yesterday.

Seems this is an upstream issue, and not related with `appimaged`.

Will ask there for improvements to their packaging process.
