### ISSUE TITLE
not work and display message "Not running on one of the supported live system"

### ISSUE THREAD

**Issue by Augusto7743** [probonopd/go-appimage#169]
Trying use appimaged and not work in Lubuntu 21.04 64 bits displaying message.
"Not running on one of the supported live system. This configuration is currently unsupported but may still work, please give feedback"
Only downloaded the appimaged appimage executable file.
Need dependencies ?

**Comment by CalebQ42** [comment]
This message didn't mean it isn't working, it's more of a warning that something MIGHT go wrong since you aren't in the distro appimaged was built with/tested with. That being said it should be working fine. You can always test it by downloading an AppImage and seeing if it shows up in your applications list.

**Comment by Augusto7743** [comment]
Thanks for your reply.
Unhappily not work.

**Comment by CalebQ42** [comment]
Could you give the output when you run appimaged?

**Comment by Augusto7743** [comment]
output ? when starting appimaged is displayed an little window in top right with the message
""Not running on one of the supported live system. This configuration is currently unsupported but may still work, please give feedback"
seeing in task manager HTOP not is displayed any executable with name appimaged.
Not is created links in start menu starting another appimages exeutables.
I had posted here only because the message say "give feedback"

**Comment by CalebQ42** [comment]
Sorry if I wasn't clear; what I meant was run the appimaged AppImage from the terminal and give what it outputs.

**Comment by Augusto7743** [comment]
appimaged-646-x86_64.AppImage 646
2021/09/10 06:06:01 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2021/09/10 06:06:01 main: PATH: /usr/local/bin:/opt:/home/AX1/Applications:/home/AX1/Desktop:/home/AX1/Downloads:/tmp/.mount_appimajxE4Tf/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
This process based on /proc/self/exe: /tmp/.mount_appimajxE4Tf/usr/bin/appimaged
Terminating other running processes with that name...
In the future, would send SIGTERM to 3657
[sudo] password for AX1: 
2021/09/10 06:06:05 Deleted 0 desktop files from /home/AX1/.local/share/applications/; use -v to see details
2021/09/10 06:06:06 Probably not launched by systemd (please file an issue if this is wrong)
2021/09/10 06:06:06 Manually launched, not by systemd. Check if enabled in systemd...
2021/09/10 06:06:06 /etc/systemd/user/appimaged.service does not exist
2021/09/10 06:06:06 Creating $XDG_CONFIG_HOME/systemd/user/appimaged.service
2021/09/10 06:06:06 thisai.path: /BTRFS/Data Files Server/Free Download Manager/1/appimaged-646-x86_64.AppImage
2021/09/10 06:06:06 /usr/bin/systemctl --user status appimaged
2021/09/10 06:06:06 exit status 3
2021/09/10 06:06:06 Restarting via systemd...

**Comment by RichardFevrier** [comment]
Same for me on elementaryOS 😕

**Comment by MrTango** [comment]
I have a similar issue on Debian Bulleye, but it's complaining about missing notification Daemon.
I'm running here with Mate Desktop and i3wm, but notifications are working.
```
$ ~/Applications/appimaged-*.AppImage
appimaged-650-x86_64.AppImage 4
2022/02/15 21:24:14 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2022/02/15 21:24:14 ERROR: notification: Message recipient disconnected from message bus without replying
2022/02/15 21:24:14 Is a notification daemon installed, and are you running on a supported system?
2022/02/15 21:24:14 main: PATH: /usr/local/bin:/opt:/home/maik/Applications:/home/maik/.local/bin:/home/maik/Desktop:/home/maik/Downloads:/tmp/.mount_appimaRVeJmM/usr/bin:/home/maik/.pyenv/plugins/pyenv-virtualenv/shims:/home/maik/.pyenv/shims:/home/maik/.pyenv/bin:/home/maik/.yarn/bin:/home/maik/.config/yarn/global/node_modules/.bin:/home/maik/.nvm/versions/node/v14.17.6/bin:/home/maik/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/home/maik/bin:/home/maik/.local/bin
This process based on /proc/self/exe: /tmp/.mount_appimaRVeJmM/usr/bin/appimaged
Terminating other running processes with that name...
2022/02/15 21:24:14 appimagelauncherd.service active
2022/02/15 21:24:14 ----------------------------
2022/02/15 21:24:14 Notification:
2022/02/15 21:24:14 Other AppImage integration daemon detected
2022/02/15 21:24:14 Please uninstall appimagelauncher first, then try again
2022/02/15 21:24:14 ERROR: appwrapper: Message recipient disconnected from message bus without replying

```

**Comment by probonopd** [comment]
Please uninstall appimagelauncher first, then try again.
