### ISSUE TITLE
Created desktop entries don't work in Cinnamon

### ISSUE THREAD

**Issue by jamerst** [probonopd/go-appimage#182]
Not sure if this just a Cinnamon-related issue or not, but the generated desktop entries don't work.

It appears that Cinnamon requires the .desktop files to be executable, otherwise they don't appear in the menu and it displays this message upon attempting to open it manually from the file explorer:
![image](https://user-images.githubusercontent.com/10601770/144759263-ec9d22dd-9d06-4762-aa32-54842e77830e.png)

It's a simple fix - just make the .desktop files executable, but it makes the daemon unusable since the .desktop files are overwritten every time it restarts.

**Comment by probonopd** [comment]
It should be rather easy to change the daemon so that it marks the desktop files as executable. Strange that different desktop environments don't even seem to agree on whether those need to be executable or not.

**Comment by jamerst** [comment]
That's strange, the files definitely didn't have the execute permission, I had to set it manually.

**Comment by probonopd** [comment]
Please comment here if this can be reproduced.
