### ISSUE TITLE
Allow generated desktop entries to be customised

### ISSUE THREAD

**Issue by jamerst** [probonopd/go-appimage#183]
I have an appimage which requires some additional commands and arguments in order to launch successfully on my system. However, every time the daemon restarts my modifications to the desktop entry are overwritten.

It would be very useful if appimaged could either preserve modifications somehow, or if there was a way to customise the desktop entry for a specific appimage.

**Comment by probonopd** [comment]
Can you give a concrete example please?

Please also check what is inside the AppImage in its desktop file as the `Exec=` line.

**Comment by jamerst** [comment]
The file is generated with:
```
Exec=/home/james/.local/bin/appimaged-650-x86_64.AppImage wrap "/home/james/.local/bin/Plexamp-3.8.2.AppImage"
```

I have to change it to: 
```
Exec=env LD_PRELOAD=/usr/lib64/libcrypto.so.1.0.2o /home/james/.local/bin/appimaged-650-x86_64.AppImage wrap "/home/james/.local/bin/Plexamp-3.8.2.AppImage" "--no-sandbox"
```

The desktop file inside the appimage already has the `--no-sandbox` argument, but I still have to add it to the generated file. Unfortunately I don't have control over the contents of the appimage, the bug this is a workaround for has existed for well over a year so I don't envision it being fixed any time soon.

If customisations aren't easily possible, I guess some kind of blacklist system would suffice so that I can manage the desktop entry for this specific appimage manually.

**Comment by probonopd** [comment]
Would https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html#configure-unprivileged-sandboxes help maybe?

**Comment by jamerst** [comment]
The `unprivileged_userns_clone` kernel parameter is a Debian patch, so it's not available for non-Debian distros. I use Fedora, so I can't use it unfortunately.

The `--no-sandbox` argument seems to be a common workaround, it's used in most of the other Electron-based appimages I have installed. It works fine for those other applications though, it's only Plexamp that needs it to be added manually.

The bug that requires LD_PRELOAD is specific to Plexamp I believe, I haven't seen the issue anywhere else.

**Comment by probonopd** [comment]
> The unprivileged_userns_clone kernel parameter is a Debian patch, so it's not available for non-Debian distros. 

Are you really sure about this? I thought all distributions use the same _kernel_ - Linux.

**Comment by jamerst** [comment]
Whilst all distros use the Linux kernel, many distros will apply their own customisations on top of the kernel in the form of patches.

The `unpriviliged_userns_clone` parameter is part of [this](https://sources.debian.org/patches/linux/3.16.56-1+deb8u1/debian/add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-default.patch/) patch. This parameter does not exist in Fedora kernels, the only way to get it on Fedora would be to compile the kernel with that patch applied, which may not even work since it's potentially dependent on other Debian patches.

**Comment by probonopd** [comment]
> The unpriviliged_userns_clone parameter is part of this patch. This parameter does not exist in Fedora kernels, the only way to get it on Fedora would be to compile the kernel with that patch applied, which may not even work since it's potentially dependent on other Debian patches.

Wow! I did not know this. So are you saying that there is no way in Fedora to use Chromium and Electron without the need for `--no-sandbox`?

That would be really, really unfortunate and I think a bug should be filed against Fedora.

**Comment by jamerst** [comment]
I believe the reason why other distros haven't adopted it is due to the security implications, though that would be less of a concern for a desktop PC than it would be for a server. The security risk from apps run with `--no-sandbox` is likely greater than that from the kernel parameter in most cases.

Chromium works okay, it's only an issue for Electron apps since Electron is based on Node.js which requires a non-sandboxed environment.

It seems like the only solution for the time being is to use the `--no-sandbox` flag, that's what most Electron apps seem to have settled with.

**Comment by probonopd** [comment]
Wow!

So the proper solution is:

* Unpack the AppImage
* Add the `--no-sandbox` argument to the command inside the AppImage that executes Chromium
* Repack the AppImage
* Get the author of the AppImage to provide a fixed AppImage

**Comment by jamerst** [comment]
That's the strange thing about this particular AppImage - it already has the `--no-sandbox` argument inside the image, but I have to add it to the .desktop file as well.

To be honest I might just use the third party flatpak version of the app, it seems to be more reliable.

**Comment by probonopd** [comment]
Please report this issue to the author of the AppImage. Which one is it?
Possibly Electron Builder needs to be changed to add the `--no-sandbox` by default.
