### ISSUE TITLE
Create flag ` --runtime-file`

### ISSUE THREAD

**Issue by lil5** [probonopd/go-appimage#188]
```
WARNING:appimagetool:flag provided but not defined: -runtime-file
```

This was generated by appimage-builder maybe including an empty flag to allow for fake backward compatibility would be great, this flag would not be handled but atleast the show can go on.

**Comment by probonopd** [comment]
This is not an error message that is coming from https://github.com/probonopd/go-appimage. Hence cosing here.

**Comment by lil5** [comment]
@probonopd Indeed you are correct, this was a tool called `appimage-builder` [link](https://appimage-builder.readthedocs.io/en/latest/intro/overview.html) that uses appimagetool.

I was having trouble getting appimagetool working on Github Actions so I thought I'll try using go-appimage (renaming the binary to appimagetool) instead, turned out that `appimage-builder` used a flag in appimagetool that go-appimage does not have.

:open_hands:  I'm trying to fully explain the issue, no aggravation is intended,

If go-appimage is trying to become a replacement of appimagetool then I would assume that this issue is still relevant.
