### ISSUE TITLE
Orphaned desktop files when dealing with automaticaly updating AppImage

### ISSUE THREAD

**Issue by zevlee** [probonopd/go-appimage#190]
When dealing with an AppImage which automatically updates, the desktop file for the previous binary is not deleted. Two programs that have this problem are Standard Notes and Bitwarden.

![Screenshot from 2022-02-11 16-21-30](https://user-images.githubusercontent.com/60147316/153681318-2d91b2ed-26ea-4117-94d5-aebae015502d.png)

After restarting, the old binary is deleted and the new one is downloaded and placed in the same folder. The notification triggers for "Added Bitwarden" but there is none which indicates that the previous version is removed. Now, there are two shortcuts, with the older of the two not working. The desktop file referencing the now deleted application still exists in ``~/.local/share/applications`` and can be easily removed by simply deleting the file.

It may be worth noting that both Standard Notes and Bitwarden are Electron-based.

I am using the amd64 AppImage on Fedora 35.

**Comment by probonopd** [comment]
"Updating" an AppImage normally means that you should get the new version in addition to the old version.

> After restarting, the old binary is deleted and the new one is downloaded and placed in the same folder. 

This behavior is not what we envision for AppImage.

**Comment by zevlee** [comment]
> Does the same thing happen if you delete an AppImage manually?

Manually deleting an AppImage functions as intended.

The orphaned desktop file only occurs as a result of an AppImage like Standard Notes or Bitwarden using their inbuilt update process. For whatever reason, appimaged doesn't detect that the previous AppImage gets deleted.

**Comment by probonopd** [comment]
> The orphaned desktop file only occurs as a result of an AppImage like Standard Notes or Bitwarden using their inbuilt update process. For whatever reason, appimaged doesn't detect that the previous AppImage gets deleted.

Interesting. This would need to be further analyzed. I don't know hat their updater is doing internally, and how this translates to inotify events (which tell appimaged that something has changed).

**Comment by zevlee** [comment]
I found a clue. ``appimaged`` is unable to detect if an AppImage is deleted with a terminal command. For example, when I run ``rm standard-notes-3.13.0-linux-x86_64.AppImage`` while in the ``~/Applications`` directory, the desktop file is not deleted. It looks to be the same for any scripts which delete an AppImage. The daemon is only able to detect when I move or delete an AppImage in my GUI file manager.

**Comment by DEVLOPRR** [comment]
It's because appimaged integrates the AppImage To the desktop, which means even after deleting the AppImage from the directory it is not de-integrated, and that's why it's still shown in the menus and other stuff.
