### ISSUE TITLE
KDE Neon

### ISSUE THREAD

**Issue by ktoulgaridis** [probonopd/go-appimage#191]
Hey there, I am using appimaged on KDE neon. 
It works properly discovering applications in the designated directories, I get notifications when I add or remove applications yet I still get a notification denoting `Not running on a Supported Live System`. 
I suppose you could go ahead and add it to the supported distros?

**Comment by probonopd** [comment]
if you can confirm that it is working properly, I'd be happy to add KDE Neon to the whitelist.
Would you like to send a pull request? Thanks.
