### ISSUE TITLE
appimaged desktop files: Arguments are not passed correctly

### ISSUE THREAD

**Issue by lawl** [probonopd/go-appimage#192]
Steps to reproduce:

1) Download an appimage
2) let appimaged generate a desktop file
3) cause arguments to be passed to the application: e.g. download https://freetubeapp.io/ which registers `MimeType=x-scheme-handler/freetube` to handle `freetube://` urls.
4) Open a freetube URL, e.g. `freetube://https://www.youtube.com/watch?v=dQw4w9WgXcQ` with `xdg-open`

Expected behaviour: FreeTube opens and starts playing rickroll.

Actual behavior: FreeTube opens and doesn't play anything.

The generated desktop file contains this exec line:

    Exec=/home/user/Applications/appimaged-650-x86_64.AppImage wrap "/home/user/Applications/freetube.AppImage"

but it should really be

    Exec=/home/user/Applications/appimaged-650-x86_64.AppImage wrap "/home/user/Applications/freetube.AppImage" %U

so that the arguments are passed correctly.

**Comment by DEVLOPRR** [comment]
I installed [github desktop](https://github.com/shiftkey/desktop) version 2.9.4 using my tool [bread](https://github.com/DEVLOPRR/bread) and for some reason it didn't register github desktop's URL protocols, like when going in that url with that protocol even after selecting the application to launch it didn't work, instead i had to add that app to default applications
