### ISSUE TITLE
appimaged does not work on Zorin 16

### ISSUE THREAD

**Issue by charizard-knows** [probonopd/go-appimage#198]
I used the instructions from [here](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md)
I am using Zorin 16, based on Ubuntu 21.04 and I am not using Appimage launcher 
After installing, I copied a Bitwarden Appimage in the ~/Applications folder and Logged out and Logged in. The daemon did not work, as the application was not visible via menu. 
Checked with other appimages in ~/Downloads folder as well.

Attaching the terminal session in case you can find something useful
[appimaged log.txt](https://github.com/probonopd/go-appimage/files/8546266/appimaged.log.txt)

**Comment by probonopd** [comment]
Please retry e.g., on Xubuntu.
