### ISSUE TITLE
appimaged does not work on AppImages with zstd compression

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#202]
Hello @CalebQ42, I have updated the AppImages generated by this project to use zstd compression.

Unfortunately appimaged seems to not work on those AppImages. Can it be that zstd compression is not working in the version of the squashfs implementation that we are using here? Or is the issue something else?

Note to self:

`/usr/bin/systemctl -l --no-pager  --user status appimaged`

shows the systemctl log.

**Comment by CalebQ42** [comment]
The version used _should_ have support for zstd.

**Comment by probonopd** [comment]
Would appreciate if you could have a look @CalebQ42 why the AppImages from https://github.com/probonopd/go-appimage/releases/tag/continuous are not being integrated. Thanks!

**Comment by CalebQ42** [comment]
I'll look into it some more, but it seems there is something else wrong. When trying to open mkappimage and appimaged's archive, it's failing because the magic number isn't correct. It looks like somehow the offset to where the archive starts isn't being read correctly.

**Comment by CalebQ42** [comment]
It seems unsquashfs has the same issue.

**Comment by CalebQ42** [comment]
Very weird, as nothing that was changed should have broken this...

Specifically I'm now getting an offset of 0 for some reason. I'll try rebuilding the AppImages to see if it's something weird with this specific build.

**Comment by probonopd** [comment]
I have also switched to a different AppImage runtime. Probably the bug is there. Sorry for the noise!

**Comment by probonopd** [comment]
The magic bytes seem correct:

```
# Old
% hexdump /tmp/runtime-x86_64 | head -n 1
0000000 457f 464c 0102 0001 4941 0002 0000 0000

# New
% hexdump /tmp/runtime-fuse2-x86_64 | head -n 1
0000000 457f 464c 0102 0001 4941 0002 0000 0000
```

**Comment by CalebQ42** [comment]
Weird... if the headers are correct, then the problem probably resides in `goappimage` and how it reads the header. But again, no changes were made that should break that...

**Comment by probonopd** [comment]
Indeed unsquashfs doesn't extract all files...

```
% chmod +x ./appimaged-661-x86_64.AppImage

%  ./appimaged-661-x86_64.AppImage --appimage-offset 
553272

% unsquashfs -o 553272 ./appimaged-661-x86_64.AppImage
Parallel unsquashfs: Using 2 processors
7 inodes (18 blocks) to write

[=============================================================================|     ] 17/18  94%

created 6 files
created 3 directories
created 0 symlinks
created 0 devices
created 0 fifos

% find squashfs-root 
squashfs-root
squashfs-root/AppRun
squashfs-root/usr
squashfs-root/usr/bin
squashfs-root/.DirIcon
```

but  `--appimage-extract` does... what gives?

```
%  ./appimaged-661-x86_64.AppImage --appimage-extract
squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/appimage.png
squashfs-root/appimaged.desktop
squashfs-root/usr
squashfs-root/usr/bin
squashfs-root/usr/bin/appimaged
squashfs-root/usr/bin/bsdtar
squashfs-root/usr/bin/unsquashfs
```

**Comment by CalebQ42** [comment]
I found the source of the issue with appimaged. It seems like the header is somehow messed up, as it isn't matching the magic number for type 2 AppImages. It's finding 410000 instead of 414902.

**Comment by CalebQ42** [comment]
`
❯ hexdump appimaged-655-x86_64.AppImage | head -n 1
0000000 457f 464c 0102 0001 4941 0002 0000 0000
❯ hexdump appimaged-661-x86_64.AppImage | head -n 1
0000000 457f 464c 0102 0001 0041 0000 0000 0000
`

**Comment by CalebQ42** [comment]
The push you just did to [static-tools](https://github.com/probonopd/static-tools) must have fix the issue. I just did a new build and everything is working now.

**Comment by probonopd** [comment]
Excellent. Sometimes oen is blind for one's own mistakes. Seems like one must **not** strip the binary _after_ inserting the magic bytes. Thanks for your help and sorry for the noise.

**Comment by CalebQ42** [comment]
No problem! I'm always happy to help, whether or not I actually end up doing anything 😋.
