### ISSUE TITLE
Consolidate .yml files in .github/workflows

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#204]
Consolidate .yml files in .github/workflows so that we only need one.

@CalebQ42 what was the logic behind splitting it up into two?
Currently everything needs to be edited in 2 places, which is error-prone.

**Comment by CalebQ42** [comment]
I think it was as simple as I somehow missed the ability to do if as part of the yml, so it was to make sure that PRs didn't get uploaded.

**Comment by probonopd** [comment]
That's what I figured ;-) I've consolidated them now. Let me know if you have concerns. Thanks!
