### ISSUE TITLE
AppImaged wrap return invalid memory error on Fedora 36 KDE

### ISSUE THREAD

**Issue by dandreossi** [probonopd/go-appimage#210]
When I run some AppImage file with the command 

`appimaged-709-x86_64.AppImage wrap "someApp.AppImage"`

I get this error and the AppImage does not start:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x70d2d0]

goroutine 44 [running]:
gopkg.in/ini%2ev1.(*File).SectionsByName(0x0, {0x2efa40?, 0x0?})
        gopkg.in/ini.v1@v1.63.0/file.go:150 +0x70
gopkg.in/ini%2ev1.(*File).GetSection(...)
        gopkg.in/ini.v1@v1.63.0/file.go:137
gopkg.in/ini%2ev1.(*File).Section(0x10000000000?, {0x2efa40, 0xd})
        gopkg.in/ini.v1@v1.63.0/file.go:169 +0x28
main.findDesktopFilesPointingToExecutable({0x7ffe87f7791a, 0x35})
        github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:160 +0x25a
main.checkDesktopFiles({0x7ffe87f7791a, 0x35})
        github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:174 +0x27
created by main.appwrap
        github.com/probonopd/go-appimage/src/appimaged/appwrapper.go:36 +0x18c
```
        
I cannot understand what's causing this issue.

**Comment by CalebQ42** [comment]
Can you provide a link to an AppImage you're having issues with. And does it seem like this is happening with all AppImages you've tried, or just one?

**Comment by dandreossi** [comment]
I'm using this.
https://www.navicat.com/download/direct-download?product=navicat16-premium-en.AppImage&location=1

I've tried also with the old version (Navicat Premium 15) and getting same error

https://www.navicat.com/en/download/direct-download?product=navicat15-premium-en.AppImage&location=1

**Comment by dandreossi** [comment]
Even with your build the issue is still here.

Don't know if it can help, but I must say that by launching the AppImage directly, I've no issue and the program run regularly.

If you have any suggestions for some test that I can perform, I will be happy to try them.

**Comment by dandreossi** [comment]
Can this problem have some qt dependencies related origins?

**Comment by dandreossi** [comment]
Found the problem!
If in `xdg.DataHome + "/applications/"` is present an invalid symlink, the appimaged wrapper crash, often without starting the application.

I've created a PR with a possible solution
