### ISSUE TITLE
Cannot open Neovim

### ISSUE THREAD

**Issue by muhammadz0** [probonopd/go-appimage#217]
The AppImage works, but can't open from desktop.

Running the command in .desktop file's Exec,

`/home/user/Downloads/appimaged-715-x86_64.AppImage wrap "/home/user/Downloads/nvim.appimage"`:

```
2022/08/24 22:43:44 Validating updateinformation in /home/user/Downloads/nvim.appimage
2022/08/24 22:43:45 Exit Status: 1
2022/08/24 22:43:45 Vim: Error reading input, exiting...

Vim: Finished.

2022/08/24 22:43:45 ----------------------------
2022/08/24 22:43:45 Notification:
2022/08/24 22:43:45 Cannot open Neovim
2022/08/24 22:43:45 Vim: Error reading input, exiting...

Vim: Finished.
```

**Comment by probonopd** [comment]
Interesting. I don't know what is causing the `Vim: Error reading input, exiting...`. Any hints appreciated.
