### ISSUE TITLE
Update the bundled desktop-file-validate

### ISSUE THREAD

**Issue by quyykk** [probonopd/go-appimage#226]
The bundled desktop-file-validate is out-of-date and rejects valid .desktop files that use the new keys introduced in the 1.5 spec.

This is the same issue as https://github.com/AppImage/AppImageKit/issues/1171. I would like to use the static runtime going forward, especially to support newer Ubuntu versions, and this is currently a blocker.

Thanks!

**Comment by quyykk** [comment]
@probonopd can you release a new release using the updated static tools? Thanks!

**Comment by probonopd** [comment]
Next build will have it
https://github.com/probonopd/go-appimage/commit/3b6283b3be0443f66af106927567870e4aa97829

**Comment by quyykk** [comment]
It doesn't seem to have triggered a build unfortunately.

**Comment by probonopd** [comment]
728 has it :)
