### ISSUE TITLE
appimaged stopped working

### ISSUE THREAD

**Issue by Leon5x** [probonopd/go-appimage#228]
I used appimaged for some time and it was working fine, but somehow it stopped working.
I didn't change anything. Then I tried removing everything and reinstalling it in the newest version 730, but that also didn't work. 
I am using Ubuntu 18.04.5 LTS. 
Any idea what I could check?

<details>
  <summary>Output when first starting appimaged after removal of the old one</summary>

```
user@astra:~/Applications$ ./appimaged-730-x86_64.AppImage 
appimaged-730-x86_64.AppImage 84
2022/10/27 09:45:45 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2022/10/27 09:45:45 main: PATH: /usr/local/bin:/opt:/home/user/Applications:/home/user/.local/bin:/home/user/Desktop:/home/user/Downloads:/tmp/.mount_appimanKkkic/usr/bin:/home/user/miniconda3/condabin:/home/user/.local/bin:/home/user/.local/sbin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
This process based on /proc/self/exe: /tmp/.mount_appimanKkkic/usr/bin/appimaged
Terminating other running processes with that name...
In the future, would send SIGTERM to 4867
2022/10/27 09:45:45 Deleted 0 desktop files from /home/user/.local/share/applications/; use -v to see details
2022/10/27 09:45:45 Probably not launched by systemd (please file an issue if this is wrong)
2022/10/27 09:45:45 Manually launched, not by systemd. Check if enabled in systemd...
2022/10/27 09:45:45 /etc/systemd/user/appimaged.service does not exist
2022/10/27 09:45:45 Creating ~/.config/systemd/user/appimaged.service
2022/10/27 09:45:45 thisai.path: /home/user/Applications/appimaged-730-x86_64.AppImage
2022/10/27 09:45:45 /bin/systemctl --user status appimaged
2022/10/27 09:45:45 exit status 3
2022/10/27 09:45:45 Enabling systemd service...
2022/10/27 09:45:45 Starting systemd service...
2022/10/27 09:45:45 appimaged should now be running via systemd. To check this, run
2022/10/27 09:45:45 /usr/bin/systemctl -l --no-pager --user status appimaged
```
</details>

<details>
  <summary>Output from systemctl after starting</summary>

```
user@astra:~/Applications$ systemctl -l --no-pager --user status appimaged
● appimaged.service - AppImage system integration daemon
   Loaded: loaded (/home/user/.config/systemd/user/appimaged.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-10-27 09:45:45 CEST; 1min 7s ago
 Main PID: 4914 (AppRun)
   CGroup: /user.slice/user-64050.slice/user@64050.service/appimaged.service
           ├─4914 /home/user/Applications/appimaged-730-x86_64.AppImage
           └─4919 /home/user/Applications/appimaged-730-x86_64.AppImage
```
</details>

**Comment by CalebQ42** [comment]
Are you sure it's not running? The outputs you provided show it working as intended.

**Comment by Leon5x** [comment]
Previously I could find the appimage programs which I put in the Applications folder with the standard ubuntu search function (pressing the windows key and typing the application name). Then I could start the programs and add them to favorites to stay on the sidebar permanently. Both doesn't work now. But the service is still running.
If everything would be running that should work, right?

Is there some verbose log where I could find more info on what is wrong?

**Comment by CalebQ42** [comment]
It seems like it's just not finding your AppImages. Make sure your AppImages are in one of the valid folders (your downloads folder or `~/Applications is most common`). If you do have them in said folder(s) then please link an AppImage that isn't getting detected.

**Comment by Leon5x** [comment]
My Appimages are in the `~/Applications` folder. The problem is that all Appimages in the folder aren't detected. So I guess it is not a problem with the appimages but rather something on the system that breaks everything. Because on another pc I have the same appimages in the Applications folder and it works fine. As it did on this pc before it magically stopped working at all.

I also removed bloated folders from Applications and Downloads, removed the appimaged installation according to [https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md), restarted my pc and installed it again with only [appimaged-730-x86_64.AppImage](https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-730-x86_64.AppImage) and also [Ferdium-linux-Portable-6.2.0-x86_64.AppImage](https://github.com/ferdium/ferdium-app/releases/download/v6.2.0/Ferdium-linux-Portable-6.2.0-x86_64.AppImage) in the Applications folder. Also with this setup it didn't work.

Some idea what else to reset or get the service to log verbose information?

**Comment by Leon5x** [comment]
I had some problems with the file manager and some disk related tools randomly freezing. Since removing appimaged they have solved themselve. Seems like it has been somehow crawling all huge network drives and other pcs to find appimages there. Otherwise I don't understand how it could have caused the problems. I just gave up and created the .desktop files myself. 

Is there any verbose flag to show/log exactly which folders are scanned at the moment?

**Comment by probonopd** [comment]
Yes, need to get the log from `systemd`. Unfortunately I can never remember the command to do that.

**Comment by CalebQ42** [comment]
Sorry for the delay. If your still having the issues on the latest version, can you let it run for a moment then give the log from `journalctl --user -u appimaged`.

appimaged _should_ only be checking the Applications folder on mounted volumes.
