### ISSUE TITLE
Installing on Fedora 36 doesn't work

### ISSUE THREAD

**Issue by hardBSDk** [probonopd/go-appimage#229]
I did all the installation steps but it gives permission denied errors (when the guide don't use sudo).

I tried to compile too, but "go get" needs to be "go install" and with a specified version in th end of the repo link.

**Comment by CalebQ42** [comment]
Can you provide the logs for the error you're getting? When you're trying to build it yourself, make sure you're using `scripts/build.sh`.

**Comment by hardBSDk** [comment]
> Can you provide the logs for the error you're getting? When you're trying to build it yourself, make sure you're using `scripts/build.sh`.

I did all the steps from the wiki, nothing left.

https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md
