### ISSUE TITLE
Stable naming of continuous assets?

### ISSUE THREAD

**Issue by teras** [probonopd/go-appimage#231]
This is not a bug of the code per se, it's more like a distribution proposal.

The assets provided by the continuous integration, inserts the version, i.e. the latest is versioned 730. What if this version is missing, so it would be easier for ci/;cd scripts to get the latest version of appimagetool?

Again, this is more like a suggestion :smile:

**Comment by probonopd** [comment]
```
wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
```

should do the trick. Was discussed before iirc.

**Comment by teras** [comment]
It works
