### ISSUE TITLE
Panics when user is created by systemd-homed

### ISSUE THREAD

**Issue by ananthb** [probonopd/go-appimage#238]
![Screenshot from 2022-12-24 22-47-52](https://user-images.githubusercontent.com/3133350/209445541-c7daee33-3d58-4e50-b04e-e2aada26e2ba.png)

appimaged panics if the current user is created and managed by systemd-homed.

Upstream Go issue: https://github.com/golang/go/issues/38810

**Comment by CalebQ42** [comment]
Same issue we #215. Should be fixed in #235

**Comment by probonopd** [comment]
Thanks @CalebQ42, out of curiosity, what causes this and what is the fix?

**Comment by CalebQ42** [comment]
It's simply that user.Current() only searches /etc/passwd for users and if the UID doesn't appear there, it returns an error. ATM the function that calls it doesn't do anything anyway, so I just changed it so it just returns instead of panicing.

**Comment by ananthb** [comment]
To add on, I'm working on fixing this in Go: https://go-review.googlesource.com/c/go/+/459455#message-3958c74d8449858b65ac2e73be1e078238e9f3b0

**Comment by ananthb** [comment]
Duplicate of #215
