### ISSUE TITLE
appimaged doesn't run with error "no such file or directory" 

### ISSUE THREAD

**Issue by pahaze** [probonopd/go-appimage#241]
After following the initial setup from `src/appimaged/README.md`, appimaged fails to run. I've tried manually downloading it to make sure it wasn't wget, and I still had the same issue. [Here's a Gist of all output.](https://gist.github.com/pahaze/ab7c6018546f1bf36cc996f29cd5a5ee) For my distro, I use openSUSE Tumbleweed.

![appimaged failing to run, but it exists](https://user-images.githubusercontent.com/69173292/212480028-a6bd0fb6-b4b4-4dcb-b063-6184a914ef6a.png)

**Comment by probonopd** [comment]
What is the architecture of your machine, and which distribution are you using?

**Comment by pahaze** [comment]
I'm using x86_64 (Ryzen 9 3950X), and for my distro, I'm using openSUSE Tumbleweed

**Comment by probonopd** [comment]
Does the same happen if you run it from bash?

**Comment by pahaze** [comment]
Yup, different message but same error essentially

![image](https://user-images.githubusercontent.com/69173292/212483861-9b5ebbe6-9955-498d-aeea-a05f9c8d4cc0.png)

**Comment by probonopd** [comment]
Does `strace ~/Applications/AppImages/appimaged-*.AppImage` give any useful insights?

**Comment by pahaze** [comment]
Actually, yeah. It looks like it's pointing to a nonexistant file/directory

![image](https://user-images.githubusercontent.com/69173292/212489214-7b5afaaf-fde2-46b3-945f-8aa92e5b7276.png)

**Comment by probonopd** [comment]
Check with `file ~/Applications/AppImages/appimaged-*.AppImage`.

It should something similar to this: `ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped`.

Check that whatever is reported as "interpreter" (e.g., `/lib64/ld-linux-x86-64.so.2`) actually exists on your system.

**Comment by pahaze** [comment]
It didn't leave an interpreter...

![image](https://user-images.githubusercontent.com/69173292/212496312-54e94e12-b0f8-444e-b4d8-a070d8bfc2ef.jpeg)

**Comment by probonopd** [comment]
Ah right, it's statically linked. Well, I'm not sure what's going on there.

**Comment by pahaze** [comment]
Yeah, it's pretty interesting IMO. I've never seen an error like it before

**Comment by pahaze** [comment]
I just tried the setup on my laptop (x86_64, openSUSE Tumbleweed) and it worked fine? Strange.

![image](https://user-images.githubusercontent.com/69173292/212510388-57209580-38d0-4bfa-9b8a-b73e9d5f3717.png)

**Comment by pahaze** [comment]
Interestingly, after restarting multiple times, it gave me this:

![image](https://user-images.githubusercontent.com/69173292/213059858-55e17068-a8eb-4773-881a-af55845788f1.png)
![image](https://user-images.githubusercontent.com/69173292/213060318-30b7d6d0-1659-4e67-a241-6d5bc029ebf3.png)

It's weird because not only is AppImageLauncher not installed, but also because there's no processes named `appimaged` or services named `appimagelauncherd`

![image](https://user-images.githubusercontent.com/69173292/213059946-bea0bd62-c16f-4853-9269-b03e662746d1.png)
![image](https://user-images.githubusercontent.com/69173292/213060365-4a9d1c16-f249-42bb-b34d-8dfcb169ee0a.png)
![image](https://user-images.githubusercontent.com/69173292/213060498-9fbed5ab-a5dc-4b85-bab3-51f2774f2bc8.png)

**Comment by pahaze** [comment]
Welp. Yet another restart entirely fixed it. Weird! But it works. I'll close this for now, thanks for helping :joy:
