### ISSUE TITLE
[Question] What to say to app dev when "is not a proper AppImage", "too short" ?

### ISSUE THREAD

**Issue by KaKi87** [probonopd/go-appimage#276]
Hi,

I'm using an app for which appimaged throws this error, but it doesn't explain much, and it doesn't prevent the app from working normally, so if I report it *as is* to a dev, I'm probably gonna get rejected like "it's the third party launcher's problem, not mine".

So, if it's truly the app's responsibility, then is there additional information supporting this statement that I could add, and if possible, suggestions ?

Actually, what would be even better is if you could write a special fixing documentation that I could link to (and add that link to the notification message).

Thanks

**Comment by CalebQ42** [comment]
For the `too short`, that's specifically relating to the zsync update information being malformed. The error text should probably be updated to mention that. `not a valid AppImage`, that is usually due to the AppImage not containing the "magic" number that denotes that a file is an AppImage, or the file could be corrupted.

**Comment by KaKi87** [comment]
Hmm, I searched "zsync" in the app's whole repo and found no result. Could it be non-applicable  ? The app is [Stellarium](https://github.com/Stellarium/stellarium). Thanks

**Comment by CalebQ42** [comment]
Specifically it's [https://github.com/probonopd/go-appimage/blob/master/internal%2Fhelpers%2Fupdateinformation.go#L61](this block) that's causing the error. I'll check out the AppImage to see why it's saying it's not an AppImage when I get home.

**Comment by CalebQ42** [comment]
Specifically it's [https://github.com/probonopd/go-appimage/blob/master/internal%2Fhelpers%2Fupdateinformation.go#L61](this block) that's causing the too short error. I'll check out the AppImage to see why it's saying it's not an AppImage when I get home.

**Comment by probonopd** [comment]
Thanks to https://github.com/probonopd/go-appimage/pull/271, the message should now be more explicit. Please comment here if you think this is still not fully resolved. Thanks!

**Comment by KaKi87** [comment]
How about a documentation explaining the author how to fix it ? Thanks

**Comment by probonopd** [comment]
Please refer to https://docs.appimage.org/packaging-guide/optional/updates.html and https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information. Thanks!

**Comment by KaKi87** [comment]
But, the first link says *can* and the second uses *may*, so it's optional ?

**Comment by probonopd** [comment]
Yes, update information is optional (but highly recommended) to have.

**Comment by KaKi87** [comment]
Then please remove this altogether, as it's not an error.

**Comment by probonopd** [comment]
Where are you seeing this? For an AppImage that contains no update information at all, or one that contains bad (too short) update information?

**Comment by KaKi87** [comment]
As I mentioned, the app is [Stellarium](https://github.com/Stellarium/stellarium). Thanks

**Comment by probonopd** [comment]
Can you update it successfully using AppImageUpdate?

**Comment by probonopd** [comment]
The Stellarium AppImage contains the string "None" as update information. The string "None" is not valid update information. Hence, the AppImage is not a valid AppImage.

```
@probonopd ➜ /workspaces/go-appimage (master) $ objdump -x ./stellarium-24.1-qt5-x86_64.AppImage | grep upd
 27 .upd_info     00000400  0000000000000000  0000000000000000  0002c38f  2**0
@probonopd ➜ /workspaces/go-appimage (master) $ dd if=./stellarium-24.1-qt5-x86_64.AppImage skip=181135 bs=1 count=1024 | xxd
00000000: 4e6f 6e65 0000 0000 0000 0000 0000 0000  None............
```

**Comment by probonopd** [comment]
Opened an upstream issue:
* https://github.com/Stellarium/stellarium/issues/3726

**Comment by probonopd** [comment]
That would be a question for the appimage-builder team. If I may have an educated guess, just leave away the entire line?

**Comment by KaKi87** [comment]
Well, actually, have a look at this :

https://github.com/AppImageCrafters/appimage-builder/blob/61c8ddde9ef44b85d7444bbe79d80b44a6a5576d/appimagebuilder/modules/appimage.py#L29

So yes it's optional, but it would still use "none" by default :thinking:

**Comment by probonopd** [comment]
In any case, then it needs to be fixed there. "None" is not a valid value for update information.

**Comment by probonopd** [comment]
Hello @KaKi87

Please check the fresh version (development snapshot) of Stellarium as mentioned [here](https://github.com/Stellarium/stellarium/issues/3726#issuecomment-2106773847):
https://github.com/Stellarium/stellarium-data/releases/tag/weekly-snapshot
