### ISSUE TITLE
Howto for users is missing.

### ISSUE THREAD

**Issue by NicTanghe** [probonopd/go-appimage#277]
The wikki seems to be a breakdown of why you think its usefull.

I thi nk evryone  is better served with an howto use the program

**Comment by probonopd** [comment]
For end users, please see
https://github.com/probonopd/go-appimage/tree/master/src/appimaged

For making AppImages, please see
https://github.com/probonopd/go-appimage/tree/master/src/appimaged

Please let me know if something is not clear; ideally please send a pull requst. Thanks!

**Comment by NicTanghe** [comment]
OK that`s not what im saying.
What I'm saying is that those entries should be on the wiki page on GH.
The way it is set up now is inc readably weird UX.

**Comment by probonopd** [comment]
Thanks. Updated the wiki page.
