### ISSUE TITLE
Appimages won't work with fuse3 unless fusermount is symlinked to fusermount3

### ISSUE THREAD

**Issue by Samueru-sama** [probonopd/go-appimage#278]
Context: https://github.com/ivan-hc/AM/discussions/387

Archlinux has separate fuse2 and fuse3 packages, and they never get symlinked, so if only fuse3 is installed and you try to use an appimage that can work with fuse3 it won't actually work because it will give a missing fusermount error. 

Doing an `ln -s /usr/bin/fusermount3 /usr/bin/fusermount` fixes the issue. But I don't know if this is an intended behavior of the distro or the fuse packages themselves. And also shouldn't the appimage itself try to use fusermount3 anyway?

It seems like debian does symlink fusermount to fusermount3.

**Comment by probonopd** [comment]
https://github.com/AppImage/type2-runtime/issues/10

**Comment by probonopd** [comment]
Please try https://github.com/probonopd/go-appimage/releases/tag/continuous

**Comment by Samueru-sama** [comment]
> Please try https://github.com/probonopd/go-appimage/releases/tag/continuous

Thank you, it works now!

**Comment by probonopd** [comment]
Thanks for bringing this up and for testing. 👍
