### ISSUE TITLE
Compatible with `linuxdeployqt` parameters ?

### ISSUE THREAD

**Issue by abcfy2** [probonopd/go-appimage#291]
I use `linuxdeployqt` before, but seems currently `appimagetool` does not compatible with `linuxdeployqt` params like `-exclude-libs=<list>`, `-extra-plugins=<list>`, `-no-copy-copyright-files` and so on.

Would you please support all the other linuxdeployqt params ?

Thanks.

**Comment by probonopd** [comment]
Hi abcfy2, these are currently not implemented in go-appimage. Maybe I (or someone else) will come around to doing it at some time, but currently I am not working on it.
