### ISSUE TITLE
UDisks showexec issue on zfs

### ISSUE THREAD

**Issue by zhang-wenchao** [probonopd/go-appimage#299]
use https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bookworm%20Root%20on%20ZFS.html

![Screenshot_20240727_102109](https://github.com/user-attachments/assets/72b66faa-e70c-41a2-b09b-550a72162fbf)

https://github.com/storaged-project/udisks/issues/707

**Comment by probonopd** [comment]
It is something that needs to configured in the operating system, not something we can change from go-appimage.
