### ISSUE TITLE
No sound with bundle everything option 

### ISSUE THREAD

**Issue by ravachol** [probonopd/go-appimage#304]
Hi,

I'm trying to use go-appImage to produce a standalone version of kew: https://github.com/ravachol/kew

If I use the -s there is no sound (this is a music player), if I don't use -s, it doesn't work on musl systems, which is what we want.

Maybe there is some secret to this...that will make it work!

**Comment by probonopd** [comment]
Hi @ravachol. This is interesting. I don't know the answer, but I guess this will require some debugging with `strace` to find out what is going on. Are you familiar with using `strace` to see what fails when running `AppRun` from the AppDir?

**Comment by probonopd** [comment]
Thanks for the update @ravachol, sounds like a plan.
