### ISSUE TITLE
Latest build of Appimaged service failed to run persistently

### ISSUE THREAD

**Issue by newmindarchitech** [probonopd/go-appimage#308]
Today i just downloaded your latest build of appimaged-849(X86_64). I have stopped and disabled the user service of the previous version of appimaged-842(X86_64) and executed the latest build of appimaged-849(X86_64) but after querying the status of the service multiple times( systemctl --user status appimaged.service). The service just wouldn't run persistently after reboot and the status of the service would be updated to be auto-restarting. I have even checked the process of the service in Plasma 6 using System Monitor(application) and i would see that the process would pop in and out constantly. Right now, I am using the appimaged-832(X86_64) build and everything works fine. Can you fix the latest build of your appimaged, I would l use your latest build but not this time

**Comment by CalebQ42** [comment]
__Gaaaaaaaaa__, when in-lining a function in #307 I forgot to remove a couple returns. Fixed with #309.
