### ISSUE TITLE
Consider to update patchelf?

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#311]
So far we are intentionally using an old version of `patchelf` because at various points in time, newer versions crippled binaries.

https://git.sr.ht/~xordspar0/packages/tree/main/item/AppImage/srb2/build.sh seems to suggest that it may now be safe (and necessary?) to use a newer one?

```
# This old version of patchelf doesn't work with binaries over a certain size
# https://github.com/NixOS/patchelf/issues/305
rm squashfs-root/usr/bin/patchelf
```

Reference:

* https://github.com/AppImageCrafters/appimage-builder/issues/10#issuecomment-2451453522

**Comment by Samueru-sama** [comment]
I've been using the patchelf provided by the distro without issues, which on archlinux I would assume it is a much newer version, didn't know go-appimage was using an old one.

**Comment by probonopd** [comment]
Can reproduce the issue when not doing

https://github.com/probonopd/xordspar0-packages/blob/09174c3458056399d5d485b36fb21dd821ef27f3/AppImage/srb2/build.sh#L43

```
ERROR patchelf --set-rpath /out/srb2.AppDir/usr/bin/srb2: warning: working around a Linux kernel bug by creating a hole of 79040512 bytes in ‘/out/srb2.AppDir/usr/bin/srb2’
maximum file size exceeded
```

Probably we should just use the newer version then, in the hope that it doesn't destroy other binaries anymore...

**Comment by probonopd** [comment]
Updated patchelf to the latest released version. Hopefully it will not cause other issues, fingers crossed.

**Comment by probonopd** [comment]
@xordspar0 you should be able to remove your workaround, similar to

https://github.com/probonopd/xordspar0-packages/commit/0b82bfc84f20dadb49ffe3a7002316ea8407091f

**Comment by xordspar0** [comment]
Thank you! And I'll be sure to report any issues I see here.
