### ISSUE TITLE
Fix appimaged on Deepin 20 Beta

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#35]
Run Deepin 20 Beta Live ISO, then run appimaged from this repository like this:

![](https://user-images.githubusercontent.com/2480569/82551139-f7370d00-9b5f-11ea-9e9b-156b75012b38.png)

Wait for 2 minutes.

Result:

```
me@host:~$ systemctl --user status appimaged
● appimaged.service - AppImage system integration daemon
   Loaded: loaded (/home/me/.config/systemd/user/appimaged.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-05-21 12:35:30 CEST; 976ms ago
  Process: 8789 ExecStart=/home/me/Downloads/appimaged-482-x86_64.AppImage (code=exited, status=1/FAILURE)
 Main PID: 8789 (code=exited, status=1/FAILURE)

May 21 12:35:30 host systemd[3938]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
May 21 12:35:30 host systemd[3938]: appimaged.service: Failed with result 'exit-code'.
me@host:~$ cat /etc/*release
DISTRIB_ID=Deepin
DISTRIB_RELEASE=20
DISTRIB_DESCRIPTION="Deepin 20 Beta"
DISTRIB_CODENAME=apricot
PRETTY_NAME="Deepin 20 Beta"
NAME="Deepin"
VERSION_ID="20 Beta"
VERSION="20 Beta"
ID=Deepin
HOME_URL="https://www.deepin.com/"
BUG_REPORT_URL="https://bbs.deepin.org/"
```

cc @shouhuanxiaoji

**Comment by probonopd** [comment]
```
May 21 12:33:37 host appimaged[5899]: 2020/05/21 12:33:37 Error: open /home/me/.cache/thumbnails/11d4a992ceae33189f5a48f
May 21 12:33:37 host appimaged[5899]: 2020/05/21 ERROR thumbnail: stat /home/me/.cache/thumbnails/11d4a992ceae33189f5a48
May 21 12:33:37 host appimaged[5899]: 2020/05/21 12:33:37 Fail to write file: open /home/me/.cache/applications//appimag
May 21 12:33:37 host appimaged[5899]: ERROR desktop fixDesktopFile: open /home/me/.cache/applications//appimagekit_838f6
May 21 12:33:37 host systemd[3938]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
May 21 12:33:37 host systemd[3938]: appimaged.service: Failed with result 'exit-code'.

```

**Comment by probonopd** [comment]
Manual workaround:

```
ulimit -Sn 1000000
me@host:~$ LAUNCHED_BY_SYSTEMD=1 Downloads/appimaged-482-x86_64.AppImage
```

Now it runs without this error. 
How to increase this limit for processes that are run by `systemd`?

**Comment by probonopd** [comment]
It should be fixed now. Please comment if it still does not work for you.

**Comment by wanweiyang** [comment]
你好  请您上线hexchat ，有点事情找您讨论
Hello, please go online to hexchat. I'd like to discuss something with you

**Comment by wanweiyang** [comment]
你好probonopd先生 , 我是deepin的开发者 ,我是负责ARM和MIPS迁移工作的，现在ARM上编译go-appimage-matser报错  问题如下图
Hello, Mr. probonopd, I'm the developer of deepin. I'm responsible for the migration of arm and MIPs. Now, the error of go appimage matser compiled on arm is shown in the figure below
![截图录屏_20200805093931](https://user-images.githubusercontent.com/63842282/89362105-87dfac80-d6bc-11ea-9853-3223b3f04f26.png)

**Comment by wanweiyang** [comment]
![截图录屏_20200805093931](https://user-images.githubusercontent.com/63842282/89362156-a5ad1180-d6bc-11ea-92cc-7c3c2854b80f.png)

**Comment by wanweiyang** [comment]
我也尝试更换go的源地址或者代理
I also try to change the source address or proxy of go：
"export GOPROXY=https://goproxy.cn"
"export GO111MODULE=on

**Comment by probonopd** [comment]
Hello Mr. @wanweiyang. Sorry for the late response, I was on vacation.

`I/O timeout` probably means that there were some issues downloading the source code of the dependency packages?
