### ISSUE TITLE
appimagetool 489 -s deploy failure

### ISSUE THREAD

**Issue by Juuliuus** [probonopd/go-appimage#44]
Hi,

This is Julius, we had a conversation on appimage discourse re: "modern" appimages.

I tried your suggestion of -s deploy with that latest appimagetool 489. Here are what I think are the relevant failure messages:
2020/07/29 10:51:06 Find out whether Qt is a dependency of the application to be bundled...
2020/07/29 10:51:06 Detected Qt 5
2020/07/29 10:51:06 Offset of qt_prfxpath: 3561388
2020/07/29 10:51:06 Length of value of qt_prfxpath: 4
qt_prfxpath: /usr
2020/07/29 10:51:06 Got qt_prfxpath but it does not contain 'plugins'
...
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/lib/x86_64-linux-gnu/kconf_update_bin
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/lib/x86_64-linux-gnu/qt5
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/share/lintian/overrides
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/src/linux-headers-5.4.0-26/scripts
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/src/linux-headers-5.4.0-26-generic/scripts
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/src/linux-headers-5.4.0-42/scripts
2020/07/29 10:36:21 Guessed qt_prfxpath to be /usr/src/linux-headers-5.4.0-42-generic/scripts
Looking in /usr/src/linux-headers-5.4.0-42-generic/scripts/plugins
2020/07/29 10:36:21 Could not find 'plugins/platforms/libqxcb.so' in qtPrfxpath, exiting

my /usr/src/linux-headers-5.4.0-42-generic/scripts/ folder does not have a plugins folder or file.

I did check and that file does exist in my /usr/.../qt/ folder fwiw.

The file also was present in ./AppDir/usr/plugins/platforms (this appdir was pre-existing from a linuxdeploy).

I tried a "bare bones" (only a bin executable, icons, and the desktop file) appdir and had the same failure.

HTH.

**Comment by probonopd** [comment]
Hello @Juuliuus thanks for checking this out. Can you please give some more information:
* OS and version
* Qt version
* Where is your Qt from (distribution? PPA? Qt website?)
* Where is your Qt `plugins` directory located?

**Comment by probonopd** [comment]
Could it be that `libqt5gui5` and/or `libqt5gui5-gles` are not installed on your system?

If so, please install them and then try again.

**Comment by Juuliuus** [comment]
Hi,

My install is a straight Kubuntu 20.04 install.

>> OS/distribution and version
Linux juus-M6800 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

>> Qt version
5.12.8

>> Where is your Qt from (distribution? PPA? Qt website?)
Kubuntu 20.04 iso

>> Where is your Qt plugins directory located? Looking at the above,
>> probably /usr/lib/x86_64-linux-gnu/qt5/plugins? 
Correct, that is where it is located.

>> Do you have /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so? 
Yes.

>>> ~ are these installed? 
libqt5gui5 
synaptic shows it as installed.
locate cmd shows: /usr/share/lintian/overrides/libqt5gui5

ibqt5gui5-gles
This is not installed but when I tried through synaptic pkg man. it wanted to remove many, many important looking packages. I will defer on this for now.

searching around on internet there was mention of having qt5-gmake installed. I do not have that installed by default.

>> What happens if you do not use -s? (Start with an empty AppDir)
I did try several permutations of the command, all failed. I will try it again but for now must "Punt". I will not be at desk for next couple of days...will report back when I can get it done.

**Comment by Juuliuus** [comment]
Pardon me please. I have no idea what I am doing on this site to make everything "quote indented".

**Comment by probonopd** [comment]
Hi, thanks for the responses, I fixed the "quote indented" by adding a blank line after each quote.

**Comment by probonopd** [comment]
>> Do you have /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so?

> Yes.

Then we must have some nasty bug around here:

https://github.com/probonopd/go-appimage/blob/1375a6de50bcbbcbdaa2d8b76a580c66f6bf68e4/src/appimagetool/appdirtool.go#L1333-L1348

Can you spot it?

**Comment by Juuliuus** [comment]
Could it be that the "plugins" also needs a preceeding / ?None of the quessed paths have an ending /, and the could not find 'plugins/platforms/...' does not have a preceeding slash...

That will depend on what is happening in FilesWithSuffixInDirectoryRecursive(qt_prfxpath, "plugins"). But I don't really see that as being the problem because other calls to that function use similar grammar and then there would be a lot of stuff failing.

One thing I don't understand and it may be of interest:
   if helpers.Exists(result + "/platforms")

The "guessed at' messages are only printed if that conditional is true. But I checked here for several "guessed at"'s and only ../qt5 has a plugins folder that contains a platforms folder. So that's odd.

It did seem to me that other calls to FilesWithSuffixInDirectoryRecursive in that code are usually searching for files, not folders, but again since .../qt5 was successfully "guessed at" that probably isn't it either.

The FilesWithSuffixInDirectoryRecursive(qt_prfxpath, "plugins") function, it turns out, is looking for anything containing 'plugins' in its name because all of those other successes do not have a straight "plugin" file or "plugin" folder, more things like, for example:
/usr/lib/x86_64-linux-gnu/kconf_update_bin/krunnerplugins

But the condition "if helpers.Exists(result + "/platforms")" shouldn't be successful at all in most of these cases! Because most, like I said are files and therefore won't have "/platforms" folders appended on them. For instance, there is no:
/usr/lib/x86_64-linux-gnu/kconf_update_bin/krunnerplugins/platforms

 So that conditional is failing somehow? There should really only be one success (.../qt5) and yet it guesses at 7 different paths.

Further, when the conditional is true I don't see it breaking out of the conditional loop? From what I see it will go through the entire range of results and returning the last "..*plugins*.. it found?

That's all I see. HTH.

**Comment by probonopd** [comment]
Indeed something strange is going on. Thanks for your analysis.

In case you have some time, you can run Go code in your browser without installing anything using https://play.golang.org/ - maybe you can figure something out

**Comment by probonopd** [comment]
Can you post the output of

> log.Println("results", results)

on your system?

**Comment by probonopd** [comment]
I think this is fixed now @Juuliuus - please check using the latest build (start with a "fresh" AppDir)

**Comment by Juuliuus** [comment]
Super! Unfortunately, my main computer chose this time to die. So stress. I will go to an older computer and give it a go in the next days.
