### ISSUE TITLE
[Bug] Not running on one of the supported Live systems

### ISSUE THREAD

**Issue by KaKi87** [probonopd/go-appimage#46]
Hello,

> Not running on one of the supported Live systems Grab a Ubuntu, Debian, Deepin, Fedora, openSUSE, elementary OS, KDE neon,... Live ISO and try from there.

How about everything that is Debian-based, including everything that is Ubuntu-based ?

For instance, I'm running Linux Mint.

Thanks

**Comment by probonopd** [comment]
Hello, as long as it is a Live ISO system it should work. (If not, post here and I will fix it immediately.) At this time, since the software is still experimental, it will run only on Live systems, but once it has been well-tested there it will be easy to remove this restriction.

Derivatives of Ubuntu, Debian, Deepin, Fedora, openSUSE,... _should_ all work.

**Comment by KaKi87** [comment]
With all due respect, what the hell ?

Using `appimaged` in a live system defeats the purpose of enabling AppImage integration into the start menu which is meant for use in a daily basis.

Plus, since when does unstable software are prohibited for non-live usage ?

And, how accurate is the testing experience if it cannot be performed non-live ?

This is very ridiculous.

**Comment by probonopd** [comment]
> Using appimaged in a live system defeats the purpose of enabling AppImage integration into the start menu which is meant for use in a daily basis.

Why? I use nothing but Live systems as my daily driver. To learn all about my setup, have a look at https://www.youtube.com/watch?v=0sRYL9IzkRQ

> Plus, since when does unstable software are prohibited for non-live usage ?

I just want to ensure that it is not damaging anything as long as it is really bleeding-edge...

**Comment by KaKi87** [comment]
> I use nothing but Live systems as my daily driver

Then how do you preserve apps, apps data and preferences, system settings and everything, drivers, etc., at each restart ?

> I just want to ensure that it is not damaging anything as long as it is really bleeding-edge

Why do this while no one else does ?
Using unstable software is all about taking risks and as a user I assume that, you don't have the right to refuse it to me.

**Comment by probonopd** [comment]
I keep all of my apps as AppImages. I have a script that runs at runtime that does all the settings/configuration for me. I store my files online or on external media. Everything else is discarded at every reboot, which I _love_ because it always gives me a clean new system.

> Using unstable software is all about taking risks and as a user I assume that, you don't have the right to refuse it to me.

I am hearing you, so you say I should remove the restriction and you would not blame me if your computer ends up in flames?

On the other hand, isn't it easy to launch a Live ISO e.g., from USB or in a virtual machine to try something out?

**Comment by KaKi87** [comment]
What if I just want to use the new appimaged because you already deprecated the old one ?
I don't exactly have a choice here, I need this program.

**Comment by KaKi87** [comment]
> I should remove the restriction and you would not blame me if your computer ends up in flames?

It's not on you, that's what's the MIT license is for :

`THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND`

**Comment by KaKi87** [comment]
Regarding your way of life, I'm incompatible to it : everytime I have to reinstall a PC or a smartphone, must I spend 2 entire days reconfiguring everything.
I can't afford resetting everything.
Each tiny bit of cache, log, history, is necessary for me.

**Comment by probonopd** [comment]
> What if I just want to use the new appimaged because you already deprecated the old one ?
I don't exactly have a choice here, I need this program.

Well, it's not like the old one stopped working or anything - I am just not spending time on it anymore.

But I hear you... glad that you volunteer to test this thing on a non-Live system for the first time.

**Comment by probonopd** [comment]
Looking forward to your feedback on how it is working on a non-Live Linux Mint system.

**Comment by KaKi87** [comment]
> We may want to go back to the more restrictive behavior in the future

What the hell ?

**Comment by probonopd** [comment]
If you can positively report back that it works on your specific distribution, it will go on the whitelist. :)

**Comment by KaKi87** [comment]
Why wouldn't it ?
Why are you speaking like if there was a nuclear bomb hidden in the program ???

**Comment by probonopd** [comment]
My philosophy is that it is broken unless someone tested it and found out it is not broken.

**Comment by KaKi87** [comment]
Well, it seems you were right, because it was a nuclear bomb indeed. A minute after appimaged started, my whole start menu was gone, all my GUI programs seem to have been wiped and **stop, it's a joke xD** It's actually working very well. I had some appimage files in my Downloads directory, so appimaged notified me and they've been automatically added to my start menu. Then I downloaded a new one through wget and as soon as it ended, it was added too. Your software is working, stop restricting its access ^^

**Comment by probonopd** [comment]
Thank you very much for testing @KaKi87, highly appreciated.

**Comment by KaKi87** [comment]
Cinnamon. I can't remember the version, I'll check it out tomorrow at the office.

**Comment by KaKi87** [comment]
Cinnamon version : `4.4.8`.

**Comment by probonopd** [comment]
Thanks @KaKi87

**Comment by probonopd** [comment]
See? https://github.com/probonopd/go-appimage/issues/72 - it's not working for a user trying to run on a distribution that I have never intended this to run on. So we need go back to a whitelisting approach. Consider everyrhing as "not working, not supported" unless specifically tested and verified by someone. 

In fact, I have started to use FreeBSD because of this. I am sick and tired of 1,001 distributions which all are same, same, but different.

**Comment by KaKi87** [comment]
> See? #72 - it's not working for a user trying to run on a distribution that I have never intended this to run on.

It doesn't mean his computer was destroyed like if appimaged exploded like a nuclear bomb.

This situation is normal.

He's sharing his experience with you so that you can fix support for his system.

That's how open source development works.

**Comment by probonopd** [comment]
Here we go:
https://github.com/probonopd/go-appimage/issues/258

Exactly as predicted.

We should put back the message so that the daemon only runs on supported (and tested) systems, imho.

**Comment by KaKi87** [comment]
Hello,

I'm still using appimaged to this day on multiple Mint & Ubuntu computers that are working fine.

> Testing and supporting every Linux distribution is almost impossible

No one says you have to.

Also,

> Cannot see volumes come and go

What does that mean ? Personally I don't get it.

**Comment by probonopd** [comment]
appimaged does not know how to get informed about disks that are attached and unattached to the computer on this operating system.

**Comment by probonopd** [comment]
> No one says you have to.

But it leads to bug reports just like #258 when in fact that OS never was even tested.

**Comment by KaKi87** [comment]
> appimaged does not know how to get informed about disks that are attached and unattached to the computer on this operating system.

Ok, got it.

> Then these should have been added to the whitelist.

How could I have been able to report that the app works on these if these weren't whitelisted in the first place ?

See, this concept of yours doesn't make any sense.

> But it leads to bug reports just like #258 when in fact that OS never was even tested.

Which is normal.

Now you can choose to fix or not to fix.

And in the second case you can even create a blacklist and put that distro in it if you want.

But please forget the whitelist.

**Comment by probonopd** [comment]
> How could I have been able to report that the app works on these if these weren't whitelisted in the first place ?

We might have added something like `--unsupported-distribution-just-for-testing` or something like that.

People should know which systems this has been tested on.

**Comment by KaKi87** [comment]
> People should know which systems this has been tested on.

In the README.

Not like this.

**Comment by probonopd** [comment]
As predicted, people are now filing bugs on random systems, not just on the supported ones.

* https://github.com/probonopd/go-appimage/issues/293
