### ISSUE TITLE
Icons in /usr/share/icons/hicolor/256x256/ don't seem to work

### ISSUE THREAD

**Issue by Krzmbrzl** [probonopd/go-appimage#50]
If I read the code correctly, then the code looks for the presence of the icon specified in the desktop file in `appdir + /usr/share/icons/hicolor/256x256/` here:
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L369-L382

What strikes me though is that in the first check it is checked whether the icon exists at the root of the appdir. This in and of itself is not what I find interesting. Rather the fact that this code part sets the `iconFile` variable:
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L367-L369

The second check however doesn't seem to set this variable. Thus
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L386
Prints 
```
Icon file: 
```
aka: An empty String.

A few lines down however this variable is used to assemble a path to copy:
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L397

In my case this results in this error:
```
ERROR Copy .DirIcon: read .: is a directory
```

I also think it is interesting that the code above seems to create a `.DirIcon` file in the AppImage's root
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L371-L381

and a bit further down we have
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L391-L394
which seems to exactly cancel above action. Interestingly however I did not see the `Deleting pre-existing .DirIcon` message in my logs so maybe I am missing something here :thinking: 

All in all I think that maybe the functionality for icons in the respective subdir is broken atm...

**Comment by Krzmbrzl** [comment]
My suggestion to fix this would simply to set the `fileName` variable in the second choice as is done in the first one. However I don't understand the `.DirIcon` logic so I am hesitant to patch this in and provide a PR...

**Comment by probonopd** [comment]
Each AppDir, including the one inside an AppImage, needs to have a `.DirIcon` file. Hence `appimagetool` tries to find a suitable icon and copy it there.

I will have a look at the logic flaws you are pointing out later.

Reference:
https://docs.appimage.org/reference/appdir.html#general-description

**Comment by probonopd** [comment]
Say you have `icon=mygreatapp` in your `.desktop` file. Then the corresponding icon should be in `<AppDir>/usr/share/icons/hicolor/256x256/apps/mygreatapp.png`.

**Comment by Krzmbrzl** [comment]
In that case I think there's another bug in the code as the check at
https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimagetool/appimagetool.go#L369
doesn't check in `.../256x256/apps` but only in `.../256x256` :point_up:

**Comment by probonopd** [comment]
Good catch :+1:
