### ISSUE TITLE
appimaged not launching, says another daemon is running when there’s not

### ISSUE THREAD

**Issue by Igetin** [probonopd/go-appimage#72]
I’m using Fedora 31 and tried to launch appimaged via the provided AppImage file:

```
$ ./appimaged-556-x86_64.AppImage
appimaged-556-x86_64.AppImage 556
2020/10/03 14:34:40 main: PATH: /home/ige/bin:/home/ige/.local/bin:/tmp/.mount_appimaH4tlDP/usr/bin:/home/ige/.luaver/luarocks/3.3.1_5.2/bin:/home/ige/.luaver/lua/5.2.4/bin:/home/ige/.pyenv/plugins/pyenv-virtualenv/shims:/home/ige/.pyenv/shims:/home/ige/.pyenv/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ige/.luarocks/bin:/home/ige/.local/bin:/home/ige/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
This process based on /proc/self/exe: /tmp/.mount_appimaH4tlDP/usr/bin/appimaged
Terminating other running processes with that name...
In the future, would send SIGTERM to 28538
2020/10/03 14:34:40 appimagelauncherfs.service inactive
2020/10/03 14:34:40 appimagelauncherd.service inactive
2020/10/03 14:34:40 ----------------------------
2020/10/03 14:34:40 Notification:
2020/10/03 14:34:40 Other AppImage integration daemon running
2020/10/03 14:34:40 Please uninstall appimagelauncher first, then try again
```

However, there are no such services on my system. Running `systemctl list-units --full --all | grep appimage` returns nothing.

**Comment by probonopd** [comment]
Do you have appimagelauncher on your system?

**Comment by Igetin** [comment]
I did in the past, but not anymore. At least there are no such services anymore on the system according to systemctl.

**Comment by probonopd** [comment]
Please post the output of

```
which appimagelauncherd
appimagelauncherfs
ls -lh /proc/sys/fs/binfmt_misc/appimage-*
```

**Comment by Igetin** [comment]
```
$ which appimagelauncherd
/usr/bin/which: no appimagelauncherd in (/home/ige/.luaver/luarocks/3.3.1_5.2/bin:/home/ige/.luaver/lua/5.2.4/bin:/home/ige/.pyenv/plugins/pyenv-virtualenv/shims:/home/ige/.pyenv/shims:/home/ige/.pyenv/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ige/.luarocks/bin:/home/ige/.local/bin:/home/ige/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
$ which appimagelauncherfs
/usr/bin/which: no appimagelauncherfs in (/home/ige/.luaver/luarocks/3.3.1_5.2/bin:/home/ige/.luaver/lua/5.2.4/bin:/home/ige/.pyenv/plugins/pyenv-virtualenv/shims:/home/ige/.pyenv/shims:/home/ige/.pyenv/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/ige/.luarocks/bin:/home/ige/.local/bin:/home/ige/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin)
$ ls -lh /proc/sys/fs/binfmt_misc/appimage-*
ls: cannot access '/proc/sys/fs/binfmt_misc/appimage-*': No such file or directory
```

**Comment by probonopd** [comment]
Do you still have launchd services files for appimagelauncherfs and appimagelauncherd around? Maybe AppImageLauncher was not completely uninstalled?

```
2020/10/03 14:34:40 appimagelauncherfs.service inactive
2020/10/03 14:34:40 appimagelauncherd.service inactive
```

**Comment by Igetin** [comment]
Fedora uses systemd, not launchd. But I’m curious where is appimaged picking up those services, since I didn’t find any unit files for AppImageLauncher lying around. I also tried to query directly through D-Bus, but there are no matches… maybe I’m not understanding something here.

```
$ gdbus call -y -d org.freedesktop.systemd1 -o /org/freedesktop/systemd1 -m org.freedesktop.systemd1.Manager.ListUnitsByPatterns "['inactive']" "['appimagelauncher*']"
(@a(ssssssouso) [],)
```

**Comment by probonopd** [comment]
> Fedora uses systemd, not launchd. 

Sorry, that's what I meant ;-)

**Comment by probonopd** [comment]
appimaged refuses to run on systems that have/had AppImageLauncher on them, unless all traces of it are entirely removed from the system. We need to find out how to eliminate AppImageLauncher and all of its traces entirely from the system.

**Comment by Igetin** [comment]
Things I’ve tried, for documentation:

* `sudo fd -I appimagelauncher /` – 0 results
* `sudo rg --no-ignore appimagelauncher /etc /usr /var/run/systemd` – 0 results
* `sudo systemctl disable appimagelauncherd`: “Failed to disable unit: Unit file appimagelauncherd.service does not exist.”
* `sudo systemctl disable appimagelauncherfs`: “Failed to disable unit: Unit file appimagelauncherfs.service does not exist.”
* `sudo systemctl reset-failed`

Files for the program should not exist anymore, and no other unit files mention it. Appimaged still refuses to launch.

I also checked DNF’s log, which shows the uninstall event from February:

```
2020-02-19T08:39:04Z SUBDEBUG Erase: appimagelauncher-2.1.1-travis931~f6d5926.x86_64
2020-02-19T08:39:04Z INFO Removing AppImageLauncher as interpreter for AppImages
+ systemctl restart systemd-binfmt
```

So the removal process should have definitely been run, along with the [post-uninstall script](https://github.com/TheAssassin/AppImageLauncher/blob/master/resources/install-scripts/post-uninstall.in).

I don’t have more time to look into this right now. Any help is appreciated.

**Comment by probonopd** [comment]
Please try the same from a Fedora Live ISO.

**Comment by milanlinux** [comment]
I am getting the exact same problem on Xubuntu 18.04, also had appimagelauncher which I uninstalled but appimaged still claims that appimagelauncherd service exists

**Comment by probonopd** [comment]
So there must be something left... does systemd cache those things maybe?

**Comment by probonopd** [comment]
@TheAssassin do you have any idea how something might be "left over" from AppImageLauncher in systemd even if AppImageLauncher itself has been uninstalled?

**Comment by TheAssassin** [comment]
Why would appimaged recognize appimagelauncherd?

Upon uninstallation, the service can't be stopped easily. But the uninstall script suggests to reboot anyway (due to systemd-binfmtd issues), which most people do, so the process then goes away.

You can always `systemctl --user stop appimagelauncherd.service`.

**Comment by probonopd** [comment]
@hcsubser does the issue go away after a reboot?

**Comment by hcsubser** [comment]
No, I actually uninstalled appimagelauncher a long time ago, so there have been multiple reboots since I tried to run go-appimaged, but it still claims that appimagelauncher is installed

**Comment by probonopd** [comment]
> Why would appimaged recognize appimagelauncherd?

appimaged checks and refuses to run if AppImageLauncher is present on the system, to avoid a collission of the two.

https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimaged/prerequisites.go#L73-L85

Apparently, even if one completely uninstalls AppImageLauncher and reboots, some remnants seem still to be left somewhere?

**Comment by hcsubser** [comment]
Alright I actually tried it now one more time and this time it actually worked, however I have not changed anything since the last try so it is still strange

**Comment by Igetin** [comment]
> Please try the same from a Fedora Live ISO.

So, I tried the same using a Fedora 31 live USB with persistent data storage. I installed appimagelauncher via the RPM package, integrated one AppImage, uninstalled the program via DNF and rebooted the system as prompted by the uninstall script. Tried the same commands as I listed earlier, and again there were seemingly no signs of appimagelauncher on the system, but appimaged still refused to run.

Turns out there _was_ still a lingering unit file, which I found by accident:

```
~/.config/systemd/user/default.target.wants/appimagelauncherd.service
```

Earlier I had only searched `/etc`, `/usr` and `/var/run/systemd`, since I wasn’t even aware that systemd had user-specific unit files. Not sure why the unit file is created there when the program is installed via sudo. Either way, the uninstallation script of appimagelauncher certainly doesn’t get rid of that file.

Also, seems like `sudo systemctl list-units --full --all` doesn’t actually return “all” unit files of the system, _only non-user-specific ones_. You have to add `--user` to get a list of user-specific units. This seems unintuitive to me, though there’s probably a good reason for why it works that way. The same goes for the other commands: running `systemctl disable appimagelauncherd` without `--user` tells that the service “doesn’t exist”, because it doesn’t even search for the user-specific units.

---

On my main system, I removed the lingering `appimagelauncherfs.service` and `appimagelauncherd.service` files, and finally got appimaged up and running.

**Comment by TheAssassin** [comment]
@Igetin unfortunately it's not that easy to, say "stop a service for all users" upon uninstallation. These user units aren't that well engineered yet, at least with regards to packaging. I'll keep that file in mind and will think about how to be able to get rid of these files...

**Comment by probonopd** [comment]
> Turns out there was still a lingering unit file, which I found by accident:
> ~/.config/systemd/user/default.target.wants/appimagelauncherd.service

So appimaged is working as designed :+1:

**Comment by mattsches** [comment]
I had a hard time resolving this, so let me add what I did in case it might help anyone.
I found two remaining files
```
/var/lib/systemd$ fd appimage .
deb-systemd-user-helper-enabled/appimagelauncherfs.service.dsh-also
deb-systemd-user-helper-enabled/default.target.wants/appimagelauncherfs.service
```
and removed them. I also found
```
$ systemctl list-units --user --full -all | grep -i appimage
● appimagelauncherfs.service      not-found inactive dead      appimagelauncherfs.service
```
But after `systemctl --user reset-failed` and `systemctl --user daemon-reload` that remaining entry was gone, and I could successfully install `appimaged`. HTH

**Comment by bllngr** [comment]
I've just hit the same issue. I understand that "appimaged is working as designed", but this is not obvious to the user in this situation. Adding a helpful message like "Please check [the most common locations] for `appimagelauncherd`/`appimagelauncherfs` remains, remove them, and try again", or even a link to a documentation explaining the situation would go a long way.

**Comment by probonopd** [comment]
@bllngr pull requests welcome.

**Comment by rag2** [comment]
For Ubuntu users having problems with removing AppImage Launcher, and presumably Debian too, the magic was to **purge** the installed `appimagelauncher` DEB package, and then to remove the `~/.config/systemd/user/default.target.wants/appimagelauncherd.service` file.

The appimaged AppImage then performed correctly, which was very gratifying.

**Comment by rag2** [comment]
The installation instructions code block at [https://github.com/probonopd/go-appimage/tree/master/src/appimaged#initial-setup](url) could with advantage be replaced by the below, which incorporates the changes noted above:

```
# Remove pre-existing similar tools
systemctl --user stop appimaged.service || true
sudo apt-get -y purge appimagelauncher || true

# Clear local configuration file
rm ~/.config/systemd/user/default.target.wants/appimagelauncherd.service

# Clear cache
rm "$HOME"/.local/share/applications/appimage*
[ -f ~/.config/systemd/user/default.target.wants/appimagelauncherd.service ] && rm ~/.config/systemd/user/default.target.wants/appimagelauncherd.service

# Optionally, install Firejail (if you want sandboxing functionality)

# Download
mkdir -p ~/Applications
wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimaged-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2) -P ~/Applications/
chmod +x ~/Applications/appimaged-*.AppImage

# Launch
~/Applications/appimaged-*.AppImage
```

**Comment by probonopd** [comment]
Done, thanks @rag2.

**Comment by kevin201** [comment]
Spent a couple of hours today trying to install appimaged. Unistall purge, followed all the hints here.Gave up in the end.

```
appimaged-907-x86_64.AppImage 261
2025/10/26 18:21:59 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2025/10/26 18:21:59 main: PATH: /tmp/.mount_appimabDCkMC/usr/bin:/home/kevin/.nvm/versions/node/v22.2.0/bin:/home/kevin/Documents/TVChaos Notes/sql:/home/kevin/bin:/home/kevin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
This process based on /proc/self/exe: /tmp/.mount_appimabDCkMC/usr/bin/appimaged
Terminating other running processes with that name...
2025/10/26 18:21:59 appimagelauncherd.service inactive
2025/10/26 18:21:59 ----------------------------
2025/10/26 18:21:59 Notification:
2025/10/26 18:21:59 Other AppImage integration daemon detected
2025/10/26 18:21:59 Please uninstall appimagelauncher first, then try again
'''
