### ISSUE TITLE
Irregularities in appimagetool.go and appdirtool.go

### ISSUE THREAD

**Issue by Juuliuus** [probonopd/go-appimage#76]
Hi. As I mentioned at [https://discourse.appimage.org/t/is-it-possible-with-s-deploy-to-include-libraries-loaded-at-runtime/1779/40](url) I had found some irregularities while working with appimagetool.go and appdirtool.go, just things I noticed, maybe they are, or maybe are not, problems.

I don't really know if you want separate issues for each of these? So I will list them here and just let me know what to do, and I will do it. 

1. in both "-s deploy" and in "-s -l deploy" (the l switch is no longer needed I think) there are two copies of ld-linux-x86-64.so.2 in different folders(/lib64/ and in /usr/lib64/, and similar in -l deploys). The sha256 sums of  both are different. In my testing I always used the /lib64/ version and it worked.

2. In the RPath of the patched libraries one finds "$ORIGIN/gconv" which is never correct, on my builds it should be "$ORIGIN/lib/x86_64-linux-gnu/gconv". The gconv path is export'd to environment correctly, however.

3. RPaths also have an "$ORIGIN/..", doesn't hurt but doesn't help? 

4. Running "-s deploy" a second time fails in the qt5 sections, I don't know if appimagetool expects a clean, "fresh" appdir or not, but once deployed one cannot deploy again. Perhaps this is by design?

**Comment by probonopd** [comment]
4 is by design, the others are not. Thanks for reporting. Unfortunately right now I don't have the time to look into them, maybe you can have a look at the code?

**Comment by Juuliuus** [comment]
Happy to.

**Comment by Juuliuus** [comment]
Sorry I thought I had posted that I'd be happy to, but never hit comment! Anyway, here are the solutions.

== deployElf ==

The 2nd ld-linux comes from deployElf. In the slice allELFs there is a "/usr/lib64/ld-linux-x86-64.so.2" string that it found
earlier. Apparently analysis of some included libraries referred to that file and so it was added to allELFs. Since the deployInterpreter function correctly handles ld-linux from the /lib64/ folder any other references to ld-linux need to be ignored. There may be subtleties on some systems such that the routine(s) that build allELFs needs to be tightened up.

So the easy fix is to check for the ld- prefix in deployElf and ignore that/those entries. 

> if strings.HasPrefix(filepath.Base(lib), "ld-") == true {
> 	log.Println("deployElf: Ignore ", lib, "because it is already deployed...")
> 	return
> }
> 

== patchRpathsInElf ==

The:
	"$ORIGIN/."
	"$ORIGIN/.."
	"$ORIGIN/gconv"

come from the patchRpathsInElf function.

The 3 lines above come from these lib locations:
	"/home/juus/RCWork/C.AppDir/lib/x86_64-linux-gnu",
	"/home/juus/RCWork/C.AppDir/lib",
	"/home/juus/RCWork/C.AppDir/lib/x86_64-linux-gnu/gconv",

It looks strange, but, actually, they are correct but need adjustment.

The problem is that running filepath.Rel on paths that are equal, are parents of the path, or are children of the path give unexpected results, which in actuality are correct. 

But. The resulting Rel must be added back onto the "base" incoming path, the appdir.Path subtracted, and concatened Rel then Clean'd.

I tested this here, and it works great.

declare at the top this var:

> origPath := filepath.Dir(path)

change:

> relpath, err := filepath.Rel(filepath.Dir(path), libloc)

to:

> relpath, err := filepath.Rel(origPath, libloc)


Then after Rel err check put these two conditionals:

> if libloc == origPath {
> 	libloc = strings.TrimPrefix(libloc, appdir.Path)
> 	relpath = filepath.Clean(libloc + "/" + relpath)
> }
> 
> if strings.HasPrefix(origPath, libloc) == true || strings.HasPrefix(libloc, origPath) == true {
> 	libloc = strings.TrimPrefix(origPath, appdir.Path)
> 	relpath = filepath.Clean(libloc + "/" + relpath)
> }
> 

== Inconsistent filepath.Clean usage ==

On working on these problems I saw a lot of usage of 'path + "/" + path', and these more often than not were incorrect resulting in
AppDir//usr/lib/....

The resulting strings were not sent through Clean but directly used in copy.Copy which apparently calls clean itself. Just saying that this could bite some day.

**Comment by Juuliuus** [comment]
Oh. I just hadn't refreshed the page before I posted.

**Comment by Juuliuus** [comment]
And let me run more tests to make sure this doesn't have knock on effects.

**Comment by Juuliuus** [comment]
Sorry for the too early report. The RPath "fix" breaks things...let me look at longer.

**Comment by Juuliuus** [comment]
Turns out the code is good, but replaced something that was mistakenly put in the RPaths but that turned out to be necessary. 

Add this just under the origPath declaration:

> newRpathStrings = append(newRpathStrings, "$ORIGIN/.")

That had originally been in the RPaths but was an "error" caused by the reasons I mentioned above. the code fix removed it. Apparently the "error" allowed everything to run! Adding it back manually fixes it all. I tested it on dev machine and under Ubuntu 16.04

**Comment by probonopd** [comment]
Thanks for looking into it @Juuliuus. Once you have a version that is working to your satisfaction, please do open a Pull Request. Thanks a lot!

**Comment by Juuliuus** [comment]
Hi, will do.

But it does need more study. After looking at the runpaths in the libs in the qt5 folders they are also quite mixed up and often completely wrong whether using the original code, or the code with my changes. The situation is not quite as simple as I first thought... :-/

Working on it...

**Comment by Juuliuus** [comment]
Hi @probonopd 

Aye yi yi. I fixed everything so that the RUNPATH's were perfect relative paths and it broke the entire AppImage.

Turns out I had made an assumption based on my reading. My assumption was that $ORIGIN "always" referred to the payload path (ie., appdir/usr/bin). And so the report of "irregularity", and my attempt to make the RUNPATH's relative to appdir/usr/bin. But after looking deeply into it I finally realized that $ORIGIN is expanded for every file, including libraries, as files are loaded.

The upshot is that the RUNPATH's:
$ORIGIN/.
$ORIGIN/..
$ORIGIN/gconv

...are perfectly correct from the point of view of that particular library. There is no problem with the RUNPATH code, it is working absolutely correctly.

This is not the first time assumptions have bitten me, and, sadly, it probably also won't be the last...but I learned a lot.

As regards the duplicate ld-linux file. The fix below needs to be put into deployElf, and is basically the twin of an already existing conditional in patchRpathsInElf. If you want to paste this into deployElf then you can close this issue immediately. Or I can submit a pull request if you like.

>     if strings.HasPrefix(filepath.Base(lib), "ld-") == true {
>     log.Println("deployElf: Ignore ", lib, " because it is already deployed...")
>     return
>     }
>

**Comment by probonopd** [comment]
> There is no problem with the RUNPATH code, it is working absolutely correctly.

:+1:

**Comment by Juuliuus** [comment]
Yeah, fixing a non-problem creates problems.

**Comment by Juuliuus** [comment]
Hi, sorry for the delay...

I'm, like, in total learn golang mode. I find it really interesting and fun to work with and am, for a learning project, writing a menu system.

Soon I will submit a pull request for the remaining issue here. I'd also like to take a look at some of the todo's in the go-appimagetool and help if I can. Thanks for your patience...

**Comment by probonopd** [comment]
@Juuliuus I also started learning Golang on this project. Take your time!
