### ISSUE TITLE
appimaged: systemd unit file is not synced to disk before systemctl call

### ISSUE THREAD

**Issue by muhlemmer** [probonopd/go-appimage#77]
As requested by command output, I'm providing feedback about using appimaged on Gentoo. This Gentoo installation uses a systemd profile, which is optional on Gentoo. By default Gentoo comes with OpenRC. That being said, lets skip to the juicy part.

1. On first run, here was an error polling the systemd unit file (exit status 3)

````
2020/10/21 15:35:04 Manually launched, not by systemd. Check if enabled in systemd...
2020/10/21 15:35:04 /etc/systemd/user/appimaged.service does not exist
2020/10/21 15:35:04 Creating ~/.config/systemd/user/appimaged.service
2020/10/21 15:35:04 thisai.path: /home/tim/Applications/appimaged-556-x86_64.AppImage
2020/10/21 15:35:05 /bin/systemctl --user status appimaged
2020/10/21 15:35:05 exit status 3
2020/10/21 15:35:05 Enabling systemd service...
2020/10/21 15:35:05 Starting systemd service...
2020/10/21 15:35:05 Exiting...
````

2. I did some checks:

````
tim@asus ~/Applications $ systemctl status appimaged.service
Unit appimaged.service could not be found.
tim@asus ~/Applications $ ls ./config/systemd/user
ls: cannot access './config/systemd/user': No such file or directory
tim@asus ~/Applications $ ls ./config/systemd
ls: cannot access './config/systemd': No such file or directory
````

3. Without changing anything to the system (I did not create the directory) I just ran again:

````
./appimaged-556-x86_64.AppImage         
appimaged-556-x86_64.AppImage 556
2020/10/21 15:38:46 Desktop notification:  Not running on one of the supported Live systems This configuration is currently unsupported but may still work, please give feedback.
2020/10/21 15:38:46 main: PATH: /home/tim/Applications:/home/tim/.local/bin:/home/tim/Desktop:/home/tim/Downloads:/tmp/.mount_appima4GFvMz/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/10/bin:/snap/bin:/home/tim/go/bin
This process based on /proc/self/exe: /tmp/.mount_appima4GFvMz/usr/bin/appimaged
Terminating other running processes with that name...
In the future, would send SIGTERM to 263037
2020/10/21 15:38:47 Deleted 1 desktop files from /home/tim/.local/share/applications/; use -v to see details
2020/10/21 15:38:47 Probably not launched by systemd (please file an issue if this is wrong)
2020/10/21 15:38:47 Manually launched, not by systemd. Check if enabled in systemd...
2020/10/21 15:38:47 /etc/systemd/user/appimaged.service does not exist
2020/10/21 15:38:47 Creating ~/.config/systemd/user/appimaged.service
2020/10/21 15:38:47 thisai.path: /home/tim/Applications/appimaged-556-x86_64.AppImage
2020/10/21 15:38:47 Restarting via systemd...
````

4. Now, the unit file exists:

````
tim@asus ~/Applications $ ls ~/.config/systemd/user/appimaged.service
/home/tim/.config/systemd/user/appimaged.service
````

5. And the service runs fine, now:

````
tim@asus ~/Applications $ systemctl --user status appimaged.service
● appimaged.service - AppImage system integration daemon
     Loaded: loaded (/home/tim/.config/systemd/user/appimaged.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-10-21 15:39:48 EEST; 28min ago
   Main PID: 263293 (AppRun)
        CPU: 7.023s
     CGroup: /user.slice/user-1000.slice/user@1000.service/appimaged.service
             ├─263293 /home/tim/Applications/appimaged-556-x86_64.AppImage
             └─263296 /home/tim/Applications/appimaged-556-x86_64.AppImage

okt 21 15:39:49 asus appimaged[263293]: map[ro:]
okt 21 15:39:49 asus appimaged[263293]: map[group_id:1000 rw: user_id:1000]
okt 21 15:39:49 asus appimaged[263293]: 2020/10/21 15:39:49 Registering AppImages in [/home/tim/Downloads /home/tim/Desktop /home/tim/.local/bin /home/tim/Applications]
okt 21 15:39:49 asus appimaged[263293]: 2020/10/21 15:39:49 zeroconf: &{{appimaged _appimaged._tcp [] local. _appimaged._tcp.local. appimaged._appimaged._tcp.local. _services._dns-sd._udp>
okt 21 15:39:49 asus appimaged[263293]: 2020/10/21 15:39:49 Notice: Cannot introspect org.gtk.vfs.UDisks2VolumeMonitor on this system The name org.gtk.vfs.UDisks2VolumeMonitor was not pro>
okt 21 15:39:49 asus appimaged[263293]: 2020/10/21 15:39:49 monitor: Monitoring DBus session bus
okt 21 15:39:52 asus appimaged[263293]: 2020/10/21 15:39:52 main: Moved 1 desktop files to /home/tim/.local/share/applications/; use -v to see details
okt 21 15:39:52 asus appimaged[263293]: 2020/10/21 15:39:52 Desktop notification:  Added application
okt 21 15:39:53 asus appimaged[263293]: 2020/10/21 15:39:53 Ran update-desktop-database /home/tim/.local/share/applications/
okt 21 15:40:02 asus appimaged[263293]: 2020/10/21 15:40:02 Subscribing to updates for gh-releases-zsync|probonopd|go-appimage|continuous|appimaged-*-x86_64.AppImage.zsync
````

6. Downloaded subsurface, which go picked up fine by the daemon. **Point for improvement:** use proper XDG categories, so that apps go to their proper sub-menus, instead on lost+found. (This is on Plasma/KDE5).

![image](https://user-images.githubusercontent.com/5411563/96724417-7bfcb000-13b8-11eb-90f4-fcf9a8c5bec3.png)

## Regarding the missing directory

It seems like a weird and random behavior that the directory was not created on the first try. I mean, looking at the logs, the following part seemed to have executed, and leaving no reason for doubt:

https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimaged/prerequisites.go#L472-L492

`XDG_CONFIG_HOME` is unset on my system.

Only thing that comes to my mind is a unchecked error here:

https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimaged/prerequisites.go#L466

But even if an error occurs there. the `home` variable will be an empty string. In that case:

https://github.com/probonopd/go-appimage/blob/f1ebcce70dae0ab9a671604261d4fd46be88384f/src/appimaged/prerequisites.go#L483

Will evaluate to `/.config/systemd/user/`, which obviously will fail, running as normal user. Its weird... Maybe the directory creation wasn't flushed to disk imediately for other processes to see it, untill `appimaged` got terminated by the second run?

**Comment by probonopd** [comment]
Thank you @muhlemmer. Sorry you had experienced issues on Gentoo. Unfortunately I cannot support Gentoo because each installation of it tends to vary in subtle ways from others. In case you are interested in submitting a fix I would consider it, but unfortunately I will not have a way to implement or test anything related to Gentoo.

**Comment by muhlemmer** [comment]
Well, it would be safe to assume that appimaged works on any distribution running systemd. But yes, I understand your point of view of not supporting individual (and exotic) distributions.

As for the issue I was experiencing, I have a hunch about what happened, but I wasn't able (yet) to reproduce. Let me investigate a bit more. If my hunch is right, I'll submit a fix by next week..

On a other note, I went through the code and noticed some `TODO`. Are you open for PRs in this respect, or you prefer to get to them yourself?

**Comment by probonopd** [comment]
> On a other note, I went through the code and noticed some TODO. Are you open for PRs in this respect, or you prefer to get to them yourself?

Absolutely, PRs that reference a TODO are more than super welcome! :+1: 
Same goes for FIXME.

**Comment by muhlemmer** [comment]
> As for the issue I was experiencing, I have a hunch about what happened, but I wasn't able (yet) to reproduce. Let me investigate a bit more. If my hunch is right, I'll submit a fix by next week..

So, what happened was: I was compiling some stuff and that put my system under some load, including heavy swapping. So I suspected that the unit file for systemd was not yet fully written to disk / queued by the time the `systemctl` call was made. (Or my `ls` after the program returned). Practically I was unable to reproduce it again over the weekend.

So after some Googling found this: golang/go#20599. And this makes sense to be the culprit. So in order for the file to become visible for processes outside this program, the file should be `Sync`ed to disk. Remember, `systemctl` will be a sub-process of the program. However, it just signals `systemd` to read the file, which is not a sub-process of our program. If the dirty cache is not yet flushed to disk, it might be that `systemd` will not find the file.

I will submit a fix that uses the `os.File` directly, and calling `f.Sync()` before `f.Close()`
