### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by probonopd** [probonopd/go-appimage#84]
Unfortunately the build now fails.
https://github.com/probonopd/go-appimage/runs/1301568998

Seems to be related to dc8b62c?

cc @srevinsaju

**Comment by srevinsaju** [comment]
Ok, I will fix the bug in 30-45 minutes, I guess it's caused by my fix :(

I wonder why the tests passed before
I apologize for the bug

**Comment by probonopd** [comment]
Yes, it's a mystery to me too why the build succeeded on the PR but then failed once it was merged. Sometimes strange things happen ;-/

**Comment by srevinsaju** [comment]
I wonder if travis is building master instead of the PR's commits. I had got quite confused when I was porting to GitHub actions.
