### ISSUE TITLE
Use Categories= from desktop files

### ISSUE THREAD

**Issue by hcsubser** [probonopd/go-appimage#88]
appimaged created desktop files in ~/.local/share/applications but appimages do not show up in the whisker menu on xfce

The reason seems to be the fact that appimaged does not pickup the "Categories" entry of the desktop file inside of the appimage and because of that whiskermenu does not know under which category to display appimage. This probably is not needed on gnome since it has a global menu but it is probably needed on just about any other more "classic" menu

I assume this would be an easy fix(correct me if it is not) because once i manually added "Category=Game;" entry to the generated .desktop file appimage appeared in the menu like it was supposed to do

**Comment by probonopd** [comment]
Yes, right now we are not using the `Categories= `entry from `.desktop` files yet (mainly because I never use the categories anyway). Do you think it could be done with little to no performance overhead?

**Comment by hcsubser** [comment]
Well, it seems like you are already using Name= entry from the appimage I assume loading one more entry wouldn't cause that much overhead, Asassin's appimagelauncher seems like it is already doing just that and it is not bad( i think it reads even more stuff than just Name= and Category= entries), although go-appimaged is faster

**Comment by probonopd** [comment]
If someone comes up with a PR; I will merge it if performance is not noticeably degraded.

**Comment by CalebQ42** [comment]
This can be closed. Should be implemented since fb78712.
