### ISSUE TITLE
Cleaning up and restructuring - Part 1

### ISSUE THREAD

**Issue by srevinsaju** [probonopd/go-appimage#90]
![image](https://user-images.githubusercontent.com/48695438/97801485-17f6a900-1c4e-11eb-8beb-97fd8fd4a405.png)

I am restucturing `go-appimagetool` following #87 (comment) to get a better structure. This is the command line interface so far which was accompanied with the restructuring. Let me know of your ideas. comments so that I can incorporate in the PR.

It looks a bit more neater for me, but this is followed by a lot of other changes too. 

cc @probonopd

**Comment by probonopd** [comment]
This is already looking very good. :+1: 

I hope the code will not become significantly harder to read.

Only change request: please use `appimagetool`, as I name all of my command line tools in lowercase and GUI applications in Uppercase.
