### ISSUE TITLE
Can't download appimaged release for x86_64?

### ISSUE THREAD

**Issue by Leeo97one** [probonopd/go-appimage#98]
It seems the `wget` command found in the [README](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) is not working because there is no appimaged [release](https://github.com/probonopd/go-appimage/releases/tag/continuous) for x86_64.

**Comment by probonopd** [comment]
I can see
https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-584-x86_64.AppImage
right now. Please try again.

**Comment by jdmarble** [comment]
I'm now able to download the latest continuous build for x86_64. I'm guessing the problem was related to the last Travis build failure. It's a shame that the last successful build isn't available, but I suppose that's the price to pay for living on the bleeding edge. :)
